 SCREENWIDTH=32: OBJCOUNT=88: VERBCOUNT=57: TOBJCOUNT=28: ROOMCOUNT=80
 GOSUB funct_3380
funct_30()
 GOSUB funct_4400
 LL=0
 GOSUB funct_3310
 P$=X$(VAL (D$(1)))
 IF P$(1)=" " THEN P$="": GOTO funct_69
funct_63()
 IF P$(LEN(P$))=" " THEN P$=P$( TO LEN(P$)-1): GOTO funct_63
 P$=P$+" "+Y$(VAL (D$(2)))
funct_68()
 IF P$(LEN(P$))=" " THEN P$=P$( TO LEN(P$)-1): GOTO funct_68
funct_69()
 P$=P$+" "
 J$=R$+". "+"YOU ARE "+P$+D$(3 TO )+" ": GOSUB funct_4830
 GOSUB funct_3330: J$=""
 FOR I=1 TO TOBJCOUNT-1
 READ O$
 IF FLAGS(I)=0 AND OBJLOC(I)=ROOMID THEN GOSUB funct_4900
 NEXT I
 IF ROOMID=ROOM_BANQUETING_HALL AND FLAGS(48)=0 THEN J$=J$+" GRARGS FEASTING,"
 IF ROOMID=ROOM_BANQUETING_HALL AND FLAGS(48)=1 THEN J$=J$+" A SLEEPING GRARG,"
 IF ROOMID=ROOM_RUSTY_GATES OR ROOMID=ROOM_OVERGROWN_TRACK THEN J$=J$+" A PONY,"
 IF ROOMID=ROOM_SIDE_OF_A_WOODED_VALLEY THEN J$=J$+" A HERMIT,"
 IF ROOMID=ROOM_DANK_CORRIDOR AND E$(18)="N " THEN J$=J$+" AN OAK DOOR,"
 IF ROOMID=ROOM_SAFE_IN_OGBANS_CHAMBER AND FLAGS(68)=1 THEN J$=J$+" OGBAN (DEAD),"
 IF J$<>"" THEN J$=", YOU CAN SEE"+J$
 J$=J$+" AND YOU CAN GO "
 GOSUB funct_4830: PRINT " ";
 FOR I=1 TO LEN(E$(ROOMID)): IF E$(ROOMID,I)<>" " THEN PRINT E$(ROOMID,I);",";
 NEXT I: PRINT : PRINT
 R$="PARDON?": PRINT "================================"
 PRINT : PRINT : PRINT "WHAT WILL YOU DO NOW"
 INPUT I$
 IF I$="SAVE GAME" THEN GOTO funct_4630
 V$="": T$="": VERBID=0: OBJID=0
 FOR I=1 TO LEN(I$)-1
 IF I$(I)=" " AND V$="" THEN V$=I$( TO I-1)
 IF I$(I+1)<>" " AND V$<>"" THEN T$=I$(I+1 TO ): I=LEN(I$)
 NEXT I: IF T$="" THEN V$=I$
funct_340()
 IF LEN(V$)<3 THEN V$=V$+"O": GOTO funct_340
 IF V$="PLAY" THEN V$="BLO"
 U$=V$( TO 3)
 FOR I=1 TO VERBCOUNT: IF VERBS$(I*3-2 TO I*3)=U$ THEN VERBID=I: I=VERBCOUNT
 NEXT I: FLAGS(36)=0
funct_390()
 GOSUB funct_3330
 FOR I=1 TO OBJCOUNT: READ O$: IF I<=TOBJCOUNT THEN GOSUB funct_3350
 IF T$=O$ THEN OBJID=I: I=OBJCOUNT
 NEXT I
 IF OBJID=0 AND FLAGS(36)=0 AND T$>"" THEN T$=T$+"S": FLAGS(36)=1: GOTO funct_390
 IF VERBID=0 THEN VERBID=VERBCOUNT+1
 IF T$="" THEN R$="I NEED TWO WORDS"
 IF VERBID>VERBCOUNT THEN R$="TRY SOMETHING ELSE"
 IF VERBID>VERBCOUNT AND OBJID=0 THEN R$="YOU CANNOT "+I$
 IF OBJID>TOBJCOUNT OR OBJID=0 THEN GOTO funct_510
 IF VERBID=VERB_GET OR VERBID=VERB_TAKE OR VERBID=VERB_PICK OR VERBID=VERB_CLIMB OR VERBID=VERB_HOLD OR VERBID>VERB_BREAK THEN GOTO funct_510
 IF VERBID<VERBCOUNT AND OBJLOC(OBJID)<>0 THEN R$="YOU DO NOT HAVE THE "+T$: GOTO funct_30
funct_510()
 IF ROOMID=ROOM_HUGE_FALLEN_OAK AND FLAGS(35)=0 AND VERBID<>VERB_BLOW AND VERBID<>VERB_MAKE THEN R$="THE GHOST OF THE GOBLIN GUARDIAN"+" HAS GOT YOU!": GOTO funct_30
 IF VERBID=VERB_HOLD OR VERBID=VERB_SHOW OR VERBID=VERB_USE OR VERBID=VERB_REFLECT OR VERBID=VERB_WITH THEN GOTO funct_540
 IF ROOMID=ROOM_WIZARDS_LAIR AND FLAGS(63)=0 THEN R$="THE WIZARD HAS YOU IN HIS GLARE": GOTO funct_30
funct_540()
 H=VAL (STR$ (ROOMID)+STR$ (OBJID))
 GOSUB X(VERBID)
 GOTO funct_650
funct_650()
 IF FLAGS(62)=1 THEN GOTO funct_730
 IF ROOMID=ROOM_ROUGH_WATER THEN FLAGS(67)=FLAGS(67)+1: IF FLAGS(67)=10 THEN FLAGS(56)=1: R$="YOU SANK!"
 IF ROOMID=ROOM_HUGE_FALLEN_OAK AND FLAGS(35)=0 AND OBJLOC(OBJ_REEDS)<>0 THEN R$="THE GHOST OF THE GOBLIN GUARDIAN"+" GETS YOU!": FLAGS(56)=1
 IF FLAGS(56)=0 THEN GOTO funct_30
 GOSUB funct_4400: PRINT R$
 PRINT "YOU HAVE FAILED IN YOUR QUEST!"
 PRINT : PRINT "BUT YOU ARE GRANTED ANOTHER TRY"
 GOSUB funct_3360: RUN
funct_730()
 GOSUB funct_4400
 PRINT "HOOORRRRAAAYYYY!"
 PRINT
 PRINT "YOU HAVE SUCCEEDED IN YOUR"
 PRINT "QUEST AND BROUGHT PEACE TO"
 PRINT "THE LAND"
 STOP
FUNCT_MOVE()
 DIRID=VERBID
 IF DIRID=VERB_UP THEN DIRID=VERB_NORTH
 IF DIRID=VERB_DOWN THEN DIRID=VERB_SOUTH
 IF NOT ((ROOMID=ROOM_WEST_END_OF_A_BRIDGE AND DIRID=VERB_EAST) OR (ROOMID=ROOM_EAST_END_OF_A_BRIDGE AND DIRID=VERB_WEST)) OR FLAGS(64)=1 THEN GOTO funct_850
 R$="A TROLL STOPS YOU CROSSING": : RETURN
funct_850()
 IF FLAGS(64)=1 THEN FLAGS(64)=0
 IF FLAGS(51)=1 OR FLAGS(29)=1 THEN GOTO funct_900
 IF FLAGS(55)=1 THEN FLAGS(56)=1: R$="GRARGS HAVE GOT YOU!": RETURN
 IF ROOMID=ROOM_BANQUETING_HALL AND FLAGS(48)=0 THEN R$="GRARGS WILL SEE YOU!": RETURN
 IF ROOMID=ROOM_BURNTOUT_CAMPFIRE OR ROOMID=ROOM_PLOUGHED_FIELD OR ROOMID=ROOM_GRARG_SENTRY_POST OR ROOMID=ROOM_GUARD_ROOM THEN R$="A GRARG PATROL APPROACHES": FLAGS(55)=1: RETURN
funct_900()
 IF OBJLOC(OBJ_BOAT)=ROOM_INVENTORY AND ((ROOMID=ROOM_EDGE_OF_AN_ICY_LAKE AND DIRID=VERB_EAST) OR (ROOMID=ROOM_ISLAND_SHORE AND DIRID<>VERB_SOUTH)) THEN R$="THE BOAT IS TOO HEAVY": RETURN
 IF OBJLOC(OBJ_BOAT)<>0 AND ((ROOMID=ROOM_EDGE_OF_AN_ICY_LAKE AND DIRID=VERB_WEST) OR (ROOMID=ROOM_ISLAND_SHORE AND DIRID=VERB_SOUTH)) THEN R$="YOU CANNOT SWIM": RETURN
 IF ROOMID=ROOM_EDGE_OF_AN_ICY_LAKE AND OBJLOC(OBJ_BOAT)=ROOM_INVENTORY AND DIRID=VERB_WEST AND FLAGS(30)=0 THEN R$="OBJCOUNT POWER!": RETURN
 IF ROOMID=ROOM_ROUGH_WATER AND DIRID=VERB_SOUTH AND FLAGS(31)=0 THEN R$="THE BOAT IS SINKING!": : RETURN
 IF ROOMID=ROOM_BARREN_COUNTRYSIDE AND DIRID=VERB_NORTH AND FLAGS(32)=0 THEN R$="OGBAN'S BOAR BLOCKS YOUR PATH": RETURN
 IF ((ROOMID=ROOM_HOLLOW_TOMB AND DIRID=VERB_EAST) OR (ROOMID=ROOM_STALACTITES_AND_STALAGMITES AND DIRID=VERB_WEST)) AND FLAGS(45)=0 THEN R$="A PILE OF RUBBLE BLOCKS YOUR PATH": RETURN
 IF ROOMID=ROOM_6FROZEN_POND AND OBJLOC(OBJ_PLANKS)<>ROOMID THEN R$="THE ICE IS BREAKING!": RETURN
 IF ROOMID=ROOM_MAZE_OF_TUNNELS AND (DIRID=VERB_EAST OR DIRID=VERB_WEST) THEN GOSUB funct_4310
 IF ROOMID=ROOM_STALACTITES_AND_STALAGMITES AND DIRID=VERB_WEST THEN R$="PASSAGE IS TOO STEEP": RETURN
 IF ROOMID=ROOM_HIGH_GLASS_GATES AND DIRID=VERB_EAST AND FLAGS(46)=0 THEN R$="A HUGE HOUND BARS YOUR WAY": RETURN
 IF (ROOMID=ROOM_WINE_CELLAR OR ROOMID=ROOM_ROW_OF_CASKS) AND FLAGS(50)=0 THEN R$="IT IS TOO DARK": : RETURN
 IF ROOMID=ROOM_MOSAICFLOORED_HALL AND DIRID=VERB_EAST AND FLAGS(54)=0 THEN R$="MYSTERIOUS FORCES HOLD YOU BACK": RETURN
 IF ROOMID=ROOM_MOSAICFLOORED_HALL AND DIRID=VERB_SOUTH AND FLAGS(68)=0 THEN R$="YOU MET OGBAN!!!": FLAGS(56)=1: RETURN
 IF ROOMID=ROOM_WINE_CELLAR AND FLAGS(65)=0 THEN R$="RATS NIBBLE YOUR ANKLES": RETURN
 IF ROOMID=ROOM_COBWEBBY_ROOM AND (DIRID=VERB_NORTH OR DIRID=VERB_WEST) AND FLAGS(66)=0 THEN R$="YOU GET CAUGHT IN THE COBWEBS!": RETURN
 IF ROOMID=ROOM_WIZARDS_LAIR AND DIRID=VERB_WEST AND FLAGS(70)=0 THEN R$="THE DOOR DOES NOT OPEN": RETURN
 IF ROOMID=ROOM_DUSTY_LIBRARY AND FLAGS(47)=1 THEN FLAGS(68)=1
 IF ROOMID=ROOM_ROW_OF_CASKS AND DIRID=VERB_WEST AND E$(37)="EW " THEN ROOMID=ROOM_SHADY_HOLLOW: R$="THE PASSAGE WAS STEEP!": RETURN
 IF ROOMID=ROOM_BANQUETING_HALL AND DIRID=VERB_SOUTH THEN FLAGS(48)=1: FLAGS(OBJ_UNIFORM)=OBJ_STATUS_VISIBLE
 IF ROOMID=ROOM_ENTRANCE_HALL_TO_THE_PALACE AND DIRID=VERB_EAST THEN FLAGS(46)=0
 OM=ROOMID: FOR I=1 TO LEN(E$(ROOMID))
 K$=E$(OM,I)
 IF (K$="N" OR K$="U") AND DIRID=VERB_NORTH THEN ROOMID=ROOMID-10
 IF K$="E" AND DIRID=VERB_EAST THEN ROOMID=ROOMID+1
 IF (K$="S" OR K$="D") AND DIRID=VERB_SOUTH THEN ROOMID=ROOMID+10
 IF K$="W" AND DIRID=VERB_WEST THEN ROOMID=ROOMID-1
 NEXT I: R$="OK"
 IF ROOMID=OM THEN R$="YOU CANNOT GO THAT WAY"
 IF ((OM=75 AND DIRID=VERB_EAST) OR (OM=76 AND DIRID=VERB_WEST)) THEN R$="OK. YOU CROSSED"
 IF FLAGS(29)=1 THEN FLAGS(39)=FLAGS(39)+1
 IF FLAGS(39)>5 AND FLAGS(29)=1 THEN R$="BOOTS HAVE WORN OUT": : FLAGS(29)=0: OBJLOC(OBJ_BOOTS)=ROOM_NOWHERE
 RETURN
FUNCT_INVENTORY()
 GOSUB funct_3330: R$="OK": FLAGS(49)=0
 PRINT "YOU HAVE ";
 FOR I=1 TO TOBJCOUNT: READ O$: GOSUB funct_3350: IF I=1 AND OBJLOC(OBJ_COINS)=ROOM_INVENTORY AND FLAGS(44)=1 THEN O$="COIN"
 IF I=TOBJCOUNT AND OBJLOC(OBJ_APPLES)=ROOM_INVENTORY THEN GOTO funct_1270
 IF OBJLOC(I)=ROOM_INVENTORY THEN PRINT O$;",";: FLAGS(49)=1
funct_1270()
 NEXT I: IF FLAGS(49)=0 THEN PRINT "NOTHING"
 PRINT : GOSUB funct_3360: RETURN
FUNCT_GET()
 IF ((ROOMID=ROOM_STREAM_IN_A_VALLEY_BOTTOM)AND(OBJID=OBJ_WATER)) THEN R$="HOW?": RETURN
 IF ((ROOMID=ROOM_ROUGH_WATER)AND(OBJID=OBJ_WATER)) OR ((ROOMID=ROOM_MIDDLE_OF_THE_LAKE)AND(OBJID=OBJ_WATER)) THEN OBJID=OBJ_JUG: GOSUB FUNCT_FILL: RETURN
 IF OBJID=OBJ_SACKS THEN R$="TOO HEAVY!": RETURN
 IF OBJID=OBJ_HORSESHOE AND FLAGS(43)=0 THEN R$="IT IS FIRMLY NAILED ON!": RETURN
 CO=0: FOR I=1 TO TOBJCOUNT-1: IF OBJLOC(I)=ROOM_INVENTORY THEN CO=CO+1
 NEXT I: IF CO>13 THEN R$="YOU CANNOT CARRY ANY MORE": RETURN
 IF OBJID>TOBJCOUNT THEN R$="YOU CANNOT GET THE "+T$: RETURN
 IF OBJID=0 THEN RETURN
 IF OBJLOC(OBJID)<>ROOMID THEN R$="IT IS NOT HERE!"
 IF FLAGS(OBJID)=1 THEN R$="WHAT "+T$+"?"
 IF OBJLOC(OBJID)=ROOM_INVENTORY THEN R$="YOU ALREADY HAVE IT"
 IF OBJLOC(OBJID)=ROOMID AND FLAGS(OBJID)=0 THEN OBJLOC(OBJID)=ROOM_INVENTORY: R$="YOU HAVE THE "+T$
 IF OBJID=OBJ_APPLE THEN OBJLOC(OBJ_APPLES)=ROOM_NOWHERE
 IF OBJID=OBJ_APPLES THEN OBJLOC(OBJ_APPLE)=ROOM_INVENTORY
 IF OBJLOC(OBJ_HORSESHOE)=ROOM_INVENTORY AND OBJLOC(OBJ_SHIELD)=ROOM_INVENTORY AND OBJLOC(OBJ_RING)=ROOM_INVENTORY THEN FLAGS(54)=1
 IF OBJID=OBJ_BOAT AND FLAGS(30)=1 THEN OBJLOC(OBJ_SHEET)=ROOM_INVENTORY
 IF OBJID=OBJ_SHEET THEN FLAGS(30)=0
 RETURN
FUNCT_EXAMINE()
 R$="YOU SEE WHAT YOU MIGHT EXPECT!"
 IF OBJID>0 THEN R$="NOTHING SPECIAL"
 IF OBJID=OBJ_HUT OR OBJID=OBJ_MOUNTIAN_HUT THEN GOSUB FUNCT_ENTER
 IF ((ROOMID=ROOM_WHITE_COTTAGE)AND(OBJID=OBJ_CHEST)) THEN R$="IT IS EMPTY"
 IF ((ROOMID=ROOM_WHITE_COTTAGE)AND(OBJID=OBJ_POT)) THEN R$="AHA!": FLAGS(OBJ_COINS)=OBJ_STATUS_VISIBLE
 IF ((ROOMID=ROOM_ATTIC_BEDROOM)AND(OBJID=OBJ_BED)) THEN R$="OK": FLAGS(OBJ_SHEET)=OBJ_STATUS_VISIBLE
 IF OBJID=OBJ_UNIFORM THEN R$="MATCHES IN POCKET": : OBJLOC(OBJ_MATCHES)=ROOM_INVENTORY
 IF ((ROOMID=ROOM_INSCRIBED_CAVERN)AND(OBJID=OBJ_INSCRIPTIONS)) THEN R$="THERE ARE SOME LETTERS '"+G$(2)+"'"
 IF ((ROOMID=ROOM_ORCHARD)AND(OBJID=OBJ_TREES)) THEN R$="THEY ARE APPLE TREES": : FLAGS(OBJ_APPLES)=OBJ_STATUS_VISIBLE
 IF ((ROOMID=ROOM_OLD_KILN)AND(OBJID=OBJ_KILN)) OR ((ROOMID=ROOM_OLD_KILN)AND(OBJID=OBJ_OLD_KILN)) THEN R$="OK": FLAGS(OBJ_JUG)=OBJ_STATUS_VISIBLE
 IF OBJID=OBJ_KETCH THEN R$="IT IS FISHY!": FLAGS(OBJ_NET)=OBJ_STATUS_VISIBLE
 IF ((ROOMID=ROOM_SACKS_ON_THE_UPPER_FLOOR)AND(OBJID=OBJ_SACKS)) THEN R$="OK": FLAGS(OBJ_SEEDS)=OBJ_STATUS_VISIBLE
 IF ((ROOMID=ROOM_GOBLIN_GRAVEYARD)AND(OBJID=OBJ_GRAVESTONES)) THEN R$="A FADED INSCRIPTION"
 IF (((ROOMID=ROOM_MISTY_POOL)AND(OBJID=OBJ_POOL)) OR ((ROOMID=ROOM_MISTY_POOL)AND(OBJID=OBJ_MISTY_POOL))) AND FLAGS(33)=0 THEN R$="A GLIMMERING FROM THE DEPTHS": 
 IF (((ROOMID=ROOM_MISTY_POOL)AND(OBJID=OBJ_POOL)) OR ((ROOMID=ROOM_MISTY_POOL)AND(OBJID=OBJ_MISTY_POOL))) AND FLAGS(33)=1 THEN R$="SOMETHING HERE....": FLAGS(OBJ_SHIELD)=OBJ_STATUS_VISIBLE
 IF ((ROOMID=ROOM_SLUICE_GATES)AND(OBJID=OBJ_SLUICE_GATES)) OR ((ROOMID=ROOM_SLUICE_GATES)AND(OBJID=OBJ_GATES)) THEN R$="THERE IS A HANDLE"
 IF OBJID=OBJ_PHIAL THEN R$="THE LABEL READS 'POISON'": 
 IF ((ROOMID=ROOM_DUSTY_LIBRARY)AND(OBJID=OBJ_BOOKS)) THEN GOSUB funct_3290
 IF ((ROOMID=ROOM_BANQUETING_HALL)AND(OBJID=OBJ_GRARGS)) AND FLAGS(48)=1 THEN R$="VERY UGLY!"
 IF ((ROOMID=ROOM_DAMP_WELL_BOTTOM)AND(OBJID=OBJ_WALLS)) OR ((ROOMID=ROOM_DAMP_WELL_BOTTOM)AND(OBJID=OBJ_WELL_BOTTOM)) THEN R$="THERE ARE LOOSE BRICKS"
 IF ROOMID=ROOM_MOSAICFLOORED_HALL THEN R$="VERY INTERSTING!"
 IF OBJID=OBJ_FOUNTAIN OR OBJID=OBJ_PINNACLE OR OBJID=OBJ_STATUE THEN R$="INTERESTING!"
 IF ((ROOMID=ROOM_STABLE)AND(OBJID=OBJ_STABLES)) THEN R$="THERE IS A WOODEN DOOR"
 IF ((ROOMID=ROOM_STABLE)AND(OBJID=OBJ_DOOR)) THEN R$="YOU FOUND SOMETHING": FLAGS(OBJ_HORSESHOE)=OBJ_STATUS_VISIBLE
 IF ((ROOMID=ROOM_KITCHENS_OF_THE_PALACE)AND(OBJID=OBJ_KITCHENS)) THEN R$="A LARGE CUPBOARD IN THE CORNER"
 IF ((ROOMID=ROOM_ANCIENT_STONE_CIRCLE)AND(OBJID=OBJ_STONES)) OR ((ROOMID=ROOM_ANCIENT_STONE_CIRCLE)AND(OBJID=OBJ_CIRCLE)) THEN R$="THERE ARE NINE STONES"
 IF ((ROOMID=ROOM_GOBLIN_GRAVEYARD)AND(OBJID=OBJ_INSCRIPTIONS)) THEN R$="A FADED WORD - 'M R H S'": 
 RETURN
FUNCT_GIVE()
 IF ROOMID=ROOM_SIDE_OF_A_WOODED_VALLEY THEN R$="HE GIVES IT BACK!"
 IF ((ROOMID=ROOM_SIDE_OF_A_WOODED_VALLEY)AND(OBJID=OBJ_BROOCH)) THEN GOSUB funct_3210
 IF ROOMID=ROOM_WEST_END_OF_A_BRIDGE OR ROOMID=ROOM_EAST_END_OF_A_BRIDGE THEN R$="HE DOES NOT WANT IT"
 IF OBJID=OBJ_COIN AND FLAGS(44)=0 THEN R$="YOU HAVE RUN OUT!"
 IF (((ROOMID=ROOM_WEST_END_OF_A_BRIDGE)AND(OBJID=OBJ_COIN)) OR ((ROOMID=ROOM_EAST_END_OF_A_BRIDGE)AND(OBJID=OBJ_COIN))) AND FLAGS(44)>0 AND OBJLOC(OBJ_COINS)=ROOM_INVENTORY THEN R$="HE TAKES IT": FLAGS(64)=1
 IF FLAGS(64)=1 THEN FLAGS(44)=FLAGS(44)-1: IF FLAGS(44)=0 THEN OBJLOC(OBJ_COINS)=ROOM_NOWHERE
 IF OBJID=OBJ_COINS THEN R$="HE TAKES THEM ALL!": OBJLOC(OBJ_COINS)=ROOM_NOWHERE: FLAGS(64)=1: FLAGS(44)=0
 IF ((ROOMID=ROOM_OVERGROWN_TRACK)AND(OBJID=OBJ_APPLE)) AND OBJLOC(OBJ_APPLES)=ROOM_NOWHERE THEN R$="HE LEADS YOU "+"NORTH": OBJLOC(OBJ_APPLE)=ROOM_NOWHERE: ROOMID=ROOM_RUSTY_GATES
 IF (((ROOMID=ROOM_OVERGROWN_TRACK)AND(OBJID=OBJ_APPLE)) AND OBJLOC(OBJ_APPLES)=ROOM_INVENTORY) OR ((ROOMID=ROOM_OVERGROWN_TRACK)AND(OBJID=OBJ_APPLES)) THEN R$="HE LEADS YOU "+"NORTH": ROOMID=ROOM_RUSTY_GATES
 IF (((ROOMID=ROOM_RUSTY_GATES)AND(OBJID=OBJ_APPLE)) AND OBJLOC(OBJ_APPLES)=ROOM_INVENTORY) OR ((ROOMID=ROOM_RUSTY_GATES)AND(OBJID=OBJ_APPLES)) THEN R$="HE LEADS YOU "+"SOUTH": ROOMID=ROOM_OVERGROWN_TRACK
 IF ((ROOMID=ROOM_WINE_CELLAR)AND(OBJID=OBJ_APPLES)) OR ((ROOMID=ROOM_WINE_CELLAR)AND(OBJID=OBJ_BREAD)) THEN R$="THEY SCURRY AWAY": OBJLOC(OBJID)=ROOM_NOWHERE: FLAGS(65)=1
 IF ((ROOMID=ROOM_HIGH_GLASS_GATES)AND(OBJID=OBJ_BONE)) THEN FLAGS(46)=1: R$="HE IS DISTRACTED"
 IF OBJID=0 OR OBJID>TOBJCOUNT THEN RETURN
 IF ROOMID=ROOM_HIGH_GLASS_GATES OR ROOMID=ROOM_BARREN_COUNTRYSIDE THEN R$="HE EATS IT!": OBJLOC(OBJID)=ROOM_NOWHERE
 RETURN
FUNCT_SAY()
 R$="YOU SAID IT"
 IF OBJID=OBJ_MAGIC_WORDS THEN R$="YOU MUST SAY THEM ONE BY ONE!": RETURN
 IF ROOMID<>ROOM_SILVER_CHAMBER OR OBJID<OBJ_AWAKE OR OBJID>OBJ_HELP OR OBJLOC(OBJ_STONE_OF_DESTINY)<>0 THEN RETURN
 IF OBJID=OBJ_AWAKE AND FLAGS(60)=0 THEN R$="THE MOUNTAIN RUMBLES!": FLAGS(60)=1: RETURN
 IF OBJID=OBJ_GUIDE AND FLAGS(60)=1 AND FLAGS(61)=0 THEN R$="TOWERS FALL DOWN!": FLAGS(61)=1: RETURN
 IF OBJID=(FLAGS(52)+73) AND FLAGS(60)=1 AND FLAGS(61)=1 THEN FLAGS(62)=1: RETURN
 R$="THE WRONG SACRED WORD!": FLAGS(56)=1: RETURN
FUNCT_PICK()
 IF OBJID=OBJ_APPLES OR OBJID=OBJ_REEDS OR OBJID=OBJ_APPLE THEN GOSUB FUNCT_GET
 RETURN
FUNCT_WEAR()
 IF OBJID=OBJ_BOOTS THEN FLAGS(29)=1: R$="YOU ARE INVISIBLE": FLAGS(55)=0: 
 IF OBJID=OBJ_UNIFORM THEN FLAGS(51)=1: R$="YOU ARE DISGUISED": FLAGS(55)=0: 
 RETURN
FUNCT_TIE()
 IF OBJID=OBJ_SHEET OR OBJID=OBJ_ROPE THEN R$="NOTHING TO TIE IT TO!"
 IF ((ROOMID=ROOM_TOP_OF_A_DEEP_WELL)AND(OBJID=OBJ_ROPE)) THEN R$="IT IS TIED": OBJLOC(OBJ_ROPE)=ROOM_TOP_OF_A_DEEP_WELL: FLAGS(53)=1
 IF ((ROOMID=ROOM_TOP_OF_A_DEEP_WELL)AND(OBJID=OBJ_SHEET)) THEN R$="OK": FLAGS(40)=1: OBJLOC(OBJ_SHEET)=ROOM_TOP_OF_A_DEEP_WELL
 RETURN
FUNCT_CLIMB()
 IF ((ROOMID=ROOM_HIGHWALLED_GARDEN)AND(OBJID=OBJ_VINE)) AND FLAGS(38)=1 THEN R$="ALL RIGHT": ROOMID=ROOM_INSCRIBED_CAVERN
 IF OBJID=OBJ_ROPE OR OBJID=OBJ_SHEET THEN R$="NOT ATTACHED TO ANYTHING!"
 IF ((ROOMID=ROOM_HIGH_PINNACLE)AND(OBJID=OBJ_ROPE)) AND OBJLOC(OBJ_ROPE)=ROOM_HIGH_PINNACLE THEN R$="YOU ARE AT THE TOP"
 IF ((ROOMID=ROOM_TOP_OF_A_DEEP_WELL)AND(OBJID=OBJ_ROPE)) AND FLAGS(53)=1 THEN R$="GOING DOWN": ROOMID=ROOM_DAMP_WELL_BOTTOM
 IF ((ROOMID=ROOM_TOP_OF_A_DEEP_WELL)AND(OBJID=OBJ_SHEET)) AND FLAGS(40)=1 THEN ROOMID=ROOM_DAMP_WELL_BOTTOM: R$="IT IS TORN": OBJLOC(OBJ_SHEET)=ROOM_NOWHERE: FLAGS(40)=0
 IF ((ROOMID=ROOM_DAMP_WELL_BOTTOM)AND(OBJID=OBJ_ROPE)) AND FLAGS(53)=1 THEN OBJLOC(OBJ_ROPE)=ROOM_DAMP_WELL_BOTTOM: FLAGS(53)=0: R$="IT FALLS DOWN - BUMP!"
 RETURN
FUNCT_USE()
 IF ((ROOMID=ROOM_EDGE_OF_AN_ICY_LAKE)AND(OBJID=OBJ_SHEET)) THEN R$="OK": FLAGS(30)=1
 IF OBJID=OBJ_COINS OR OBJID=OBJ_COIN OR OBJID=OBJ_APPLES OR OBJID=OBJ_APPLE OR OBJID=OBJ_BONE OR OBJID=OBJ_BREAD THEN GOSUB FUNCT_GIVE
 IF ((ROOMID=ROOM_ROUGH_WATER)AND(OBJID=OBJ_BUCKET)) THEN R$="YOU HAVE KEPT AFLOAT": FLAGS(31)=1: : RETURN
 IF ((ROOMID=ROOM_ROUGH_WATER)AND(OBJID=OBJ_JUG)) THEN R$="IT IS NOT BIG ENOUGH!": RETURN
 IF OBJID=OBJ_SWORD OR OBJID=OBJ_AXE THEN GOSUB FUNCT_SWING
 IF OBJID=OBJ_PLANKS THEN GOSUB FUNCT_LEAVE
 IF OBJID=OBJ_SILVER_PLATE THEN GOSUB FUNCT_HOLD
 IF OBJID=OBJ_REEDS THEN GOSUB FUNCT_RIG
 IF OBJID=OBJ_JUG OR OBJID=OBJ_BUCKET THEN GOSUB FUNCT_FILL
 RETURN
FUNCT_OPEN()
 IF OBJID=OBJ_CHEST OR OBJID=OBJ_SACKS THEN GOSUB FUNCT_EXAMINE
 IF ((ROOMID=ROOM_KITCHENS_OF_THE_PALACE)AND(OBJID=OBJ_CUPBOARD)) THEN FLAGS(OBJ_PHIAL)=OBJ_STATUS_VISIBLE: R$="OK"
 IF ((ROOMID=ROOM_CUPBOARD_IN_A_CORNER)AND(OBJID=OBJ_CUPBOARD)) THEN R$="OK": FLAGS(OBJ_BOOTS)=OBJ_STATUS_VISIBLE
 IF ((ROOMID=ROOM_SLUICE_GATES)AND(OBJID=OBJ_GATES)) OR ((ROOMID=ROOM_DANK_CORRIDOR)AND(OBJID=OBJ_DOOR)) THEN R$="YOU ARE NOT STRONG ENOUGH"
 IF ((ROOMID=ROOM_ROW_OF_CASKS)AND(OBJID=OBJ_CASKS)) THEN R$="A PASSAGE!": E$(37)="EW"
 IF ((ROOMID=ROOM_SAFE_IN_OGBANS_CHAMBER)AND(OBJID=OBJ_SAFE)) THEN GOSUB funct_3260
 IF ((ROOMID=ROOM_STABLE)AND(OBJID=OBJ_DOOR)) THEN R$="IT FALLS OF ITS HINGES"
 IF ((ROOMID=ROOM_WIZARDS_LAIR)AND(OBJID=OBJ_DOOR)) THEN R$="IT IS LOCKED"
 RETURN
FUNCT_LIGHT()
 IF OBJID>TOBJCOUNT THEN R$="IT DOES NOT BURN"
 IF OBJID=OBJ_MATCHES THEN R$="YOU LIT THEM"
 IF ((ROOMID=ROOM_WINE_CELLAR)AND(OBJID=OBJ_MATCHES)) THEN R$="NOT BRIGHT ENOUGH"
 IF (OBJID=OBJ_LAMP OR ((ROOMID=ROOM_STABLE)AND(OBJID=OBJ_DOOR))) AND OBJLOC(OBJ_MATCHES)<>0 THEN R$="NO MATCHES": 
 IF OBJID=OBJ_LAMP AND OBJLOC(OBJ_MATCHES)=ROOM_INVENTORY THEN R$="A BRIGHT "+V$: FLAGS(50)=1
 IF ((ROOMID=ROOM_STABLE)AND(OBJID=OBJ_DOOR)) AND OBJLOC(OBJ_MATCHES)=ROOM_INVENTORY THEN FLAGS(43)=1: R$="IT HAS TURNED TO ASHES"
 RETURN
FUNCT_FILL()
 IF (OBJID=OBJ_JUG OR OBJID=OBJ_BUCKET) AND (ROOMID=ROOM_ROUGH_WATER OR ROOMID=ROOM_MIDDLE_OF_THE_LAKE) THEN R$="YOU CAPSIZED!": FLAGS(56)=1
 IF ((ROOMID=ROOM_STREAM_IN_A_VALLEY_BOTTOM)AND(OBJID=OBJ_JUG)) AND OBJLOC(OBJ_JUG)=ROOM_INVENTORY THEN R$="IT IS NOW FULL": FLAGS(34)=1
 IF ((ROOMID=ROOM_STREAM_IN_A_VALLEY_BOTTOM)AND(OBJID=OBJ_BUCKET)) THEN R$="IT LEAKS OUT!"
 RETURN
FUNCT_PLANT()
 IF OBJID<>OBJ_SEEDS OR ROOMID<>ROOM_HIGHWALLED_GARDEN THEN R$="DO NOT GROW!": RETURN
 R$="OK": FLAGS(37)=1
 RETURN
FUNCT_WATER()
 IF OBJID=OBJ_SEEDS AND FLAGS(37)=1 AND FLAGS(34)=1 THEN R$="A LARGE VINE GROWS IN SECONDS!": FLAGS(38)=1: 
 RETURN
FUNCT_SWING()
 IF OBJID=OBJ_AXE OR OBJID=OBJ_SWORD THEN R$="THWACK!"
 IF ((ROOMID=ROOM_COBWEBBY_ROOM)AND(OBJID=OBJ_SWORD)) THEN R$="YOU CLEARED THE COBWEBS": FLAGS(66)=1
 IF ((ROOMID=ROOM_DANK_CORRIDOR)AND(OBJID=OBJ_AXE)) THEN R$="THE DOOR BROKE!": E$(18)="NS": E$(28)="NS"
 IF ((ROOMID=ROOM_DAMP_WELL_BOTTOM)AND(OBJID=OBJ_AXE)) THEN R$="YOU BROKE THROUGH": E$(71)="N"
 RETURN
FUNCT_EMPTY()
 IF OBJID=OBJ_JUG THEN OBJID=OBJ_SEEDS: GOSUB FUNCT_WATER
 IF ((ROOMID=ROOM_MOSAICFLOORED_HALL)AND(OBJID=OBJ_PHIAL)) THEN R$="WHERE?"
 RETURN
FUNCT_ENTER()
 IF ((ROOMID=ROOM_55OUTSIDE_A_WINDMILL)AND(OBJID=OBJ_WINDMILL)) THEN VERBID=VERB_EAST: GOSUB FUNCT_MOVE: RETURN
 IF ROOMID=ROOM_MOUNTAIN_HUT THEN R$="YOU FOND SOMETHING": FLAGS(OBJ_PLANKS)=OBJ_STATUS_VISIBLE
 RETURN
FUNCT_CROSS()
 IF ROOMID=ROOM_EAST_END_OF_A_BRIDGE THEN VERBID=VERB_WEST: GOSUB FUNCT_MOVE: RETURN
 IF ROOMID=ROOM_WEST_END_OF_A_BRIDGE THEN VERBID=VERB_EAST: GOSUB FUNCT_MOVE
 RETURN
FUNCT_REMOVE()
 IF (OBJID=OBJ_BOOTS AND FLAGS(29)=1) THEN R$="TAKEN OFF": FLAGS(29)=0
 IF (OBJID=OBJ_UNIFORM AND FLAGS(51)=1) THEN R$="OK": FLAGS(51)=0
 IF OBJID=OBJ_BRICKS OR OBJID=OBJ_RUBBLE THEN GOSUB FUNCT_MOVE
 RETURN
FUNCT_FEED()
 IF ((ROOMID=ROOM_WINE_CELLAR)AND(OBJID=OBJ_RATS)) OR ((ROOMID=ROOM_RUSTY_GATES)AND(OBJID=OBJ_PONY)) OR ((ROOMID=ROOM_OVERGROWN_TRACK)AND(OBJID=OBJ_PONY)) OR ((ROOMID=ROOM_BARREN_COUNTRYSIDE)AND(OBJID=OBJ_OGBANS_BOAR)) OR ((ROOMID=ROOM_HIGH_GLASS_GATES)AND(OBJID=OBJ_HOUND)) THEN R$="WITH WHAT?"
 RETURN
FUNCT_TURN()
 IF ((ROOMID=ROOM_DISUSED_WATERWHEEL)AND(OBJID=OBJ_WHEEL)) THEN R$="IT GOES ROUND"
 IF ((ROOMID=ROOM_SLUICE_GATES)AND(OBJID=OBJ_HANDLE)) THEN R$="THE GATES OPEN, THE POOL EMPTIES": FLAGS(33)=1: 
 RETURN
FUNCT_DIVE()
 IF ROOMID=ROOM_MISTY_POOL OR ROOMID=ROOM_MIDDLE_OF_THE_LAKE THEN R$="YOU HAVE DROWNED": FLAGS(56)=1
 RETURN
FUNCT_BAIL()
 R$="HOW?": RETURN
FUNCT_LEAVE()
 IF OBJID=0 OR OBJID>TOBJCOUNT THEN RETURN
 OBJLOC(OBJID)=ROOMID: R$="DONE"
 IF ((ROOMID=ROOM_ROUGH_WATER)AND(OBJID=OBJ_BOAT)) OR ((ROOMID=ROOM_MIDDLE_OF_THE_LAKE)AND(OBJID=OBJ_BOAT)) THEN R$="YOU DROWNED!": FLAGS(56)=1
 IF OBJID=OBJ_BOAT AND FLAGS(30)=1 THEN OBJLOC(OBJ_SHEET)=ROOMID
 IF OBJID=OBJ_JUG AND FLAGS(34)=1 THEN R$="YOU LOST THE WATER!": FLAGS(34)=0
 IF OBJID=OBJ_SHEET AND FLAGS(30)=1 THEN FLAGS(30)=0
 RETURN
FUNCT_INSERT()
 IF OBJID=OBJ_COIN AND FLAGS(44)=0 THEN R$="YOU DO NOT HAVE ANY"
 IF ((ROOMID=ROOM_TURRET_ROOM_WITH_A_SLOT_MACHINE)AND(OBJID=OBJ_COIN)) AND OBJLOC(OBJ_COINS)=ROOM_INVENTORY AND FLAGS(44)>0 THEN GOSUB funct_3230
 RETURN
FUNCT_THROW()
 IF OBJID=0 OR OBJID>TOBJCOUNT THEN RETURN
 R$="DID NOT GO FAR!": OBJLOC(OBJID)=ROOMID
 IF ((ROOMID=ROOM_BARREN_COUNTRYSIDE)AND(OBJID=OBJ_NET)) THEN R$="YOU CAUGHT THE BOAR": FLAGS(32)=1: 
 RETURN
FUNCT_RIG()
 IF OBJID=OBJ_REEDS THEN R$="A NICE TUNE": 
 IF ((ROOMID=ROOM_EDGE_OF_AN_ICY_LAKE)AND(OBJID=OBJ_SAIL)) THEN R$="WHAT WITH?"
 IF OBJID=OBJ_MUSIC THEN R$="HOW, O MUSICAL ONE?"
 IF ((ROOMID=ROOM_HUGE_FALLEN_OAK)AND(OBJID=OBJ_REEDS)) THEN FLAGS(35)=1: R$="THE GHOST OF THE GOBLIN GUARDIAN IS FREE": E$(56)="NS"
 RETURN
FUNCT_EAT()
 IF OBJID=0 OR OBJID>TOBJCOUNT THEN RETURN
 IF OBJID=OBJ_APPLES OR OBJID=OBJ_BREAD THEN R$="YUM YUM!": OBJLOC(OBJID)=ROOM_NOWHERE
 RETURN
FUNCT_MOVE()
 IF ROOMID=ROOM_STALACTITES_AND_STALAGMITES AND OBJID=OBJ_RUBBLE THEN FLAGS(45)=1: R$="YOU REVEALED A STEEP PASSAGE"
 IF ROOMID=ROOM_HOLLOW_TOMB AND OBJID=OBJ_RUBBLE THEN R$="YOU CANNOT MOVE RUBBLE FROM HERE"
 IF ((ROOMID=ROOM_DAMP_WELL_BOTTOM)AND(OBJID=OBJ_BRICKS)) THEN R$="THEY ARE WEDGED IN!"
 RETURN
FUNCT_INTO()
 IF (OBJID=OBJ_GOBLET OR OBJID=OBJ_WINE) AND OBJLOC(OBJ_PHIAL)=ROOM_INVENTORY AND ROOMID=ROOM_MOSAICFLOORED_HALL THEN R$="OK": FLAGS(47)=1
 RETURN
FUNCT_RING()
 IF ROOMID<>ROOM_SILVER_BELL_IN_THE_ROCK OR OBJID<>OBJ_BELL THEN RETURN
funct_3020()
 PRINT : PRINT "HOW MANY TIMES?": INPUT MR: IF MR=0 THEN PRINT "A NUMBER": GOTO funct_3020
 IF MR=FLAGS(42) THEN R$="A ROCK DOOR OPENS": E$(27)="EW": RETURN
 R$="YOU HAVE MISTREATED THE BELL!": FLAGS(56)=1: : RETURN
FUNCT_CUT()
 IF ((ROOMID=ROOM_COBWEBBY_ROOM)AND(OBJID=OBJ_COBWEBS)) THEN ((ROOMID=ROOM_COBWEBBY_ROOM)AND(OBJID=OBJ_SWORD)): GOSUB FUNCT_SWING
 RETURN
FUNCT_HOLD()
 IF (((ROOMID=ROOM_WIZARDS_LAIR)AND(OBJID=OBJ_UP_SILVER_PLATE)) OR ((ROOMID=ROOM_WIZARDS_LAIR)AND(OBJID=OBJ_SILVER_PLATE))) AND OBJLOC(OBJ_SILVER_PLATE)=ROOM_INVENTORY THEN R$="YOU REFLECTED THE WIZARD'S GLARE! HE IS DEAD": FLAGS(63)=1: 
 IF OBJID=OBJ_STONE_OF_DESTINY THEN GOSUB FUNCT_GET
 RETURN
FUNCT_PAY()
 IF ((ROOMID=ROOM_WEST_END_OF_A_BRIDGE)AND(OBJID=OBJ_TROLL)) OR ((ROOMID=ROOM_EAST_END_OF_A_BRIDGE)AND(OBJID=OBJ_TROLL)) THEN R$="WHAT WITH?"
 IF OBJID=OBJ_COINS OR OBJID=OBJ_COIN THEN GOSUB FUNCT_GIVE
 RETURN
FUNCT_UNLOCK()
 IF ((ROOMID=ROOM_WIZARDS_LAIR)AND(OBJID=OBJ_DOOR)) AND OBJLOC(OBJ_KEY)=ROOM_INVENTORY THEN R$="THE KEY TURNS!": FLAGS(70)=1
 RETURN
FUNCT_BREAK()
 IF ((ROOMID=ROOM_DANK_CORRIDOR)AND(OBJID=OBJ_DOOR)) THEN R$="HOW?"
 RETURN
FUNCT_REFLECT()
 IF ROOMID=ROOM_WIZARDS_LAIR THEN R$="HOW?"
 RETURN
FUNCT_DRINK()
 R$="ARE YOU THIRSTY?"
 RETURN
funct_3210()
 R$="HE TAKES IT AND SAYS '"+STR$ (FLAGS(42))+" RINGS ARE NEEDED'": OBJLOC(OBJ_BROOCH)=ROOM_NOWHERE
 RETURN
funct_3230()
 FLAGS(44)=FLAGS(44)-1: R$="A NUMBER APPEARS - "+STR$ (FLAGS(41))
 IF FLAGS(44)=0 THEN OBJLOC(OBJ_COINS)=ROOM_NOWHERE
 RETURN
funct_3260()
 PRINT : R$="WHAT IS THE CODE": : PRINT R$: INPUT CN
 R$="WRONG!": IF CN=FLAGS(41) THEN R$="IT OPENS": FLAGS(OBJ_KEY)=OBJ_STATUS_VISIBLE
 RETURN
funct_3290()
 T=ROOMID: ROOMID=FLAGS(FLAGS(52)+57): GOSUB funct_3310: ROOMID=T
 R$="MAGIC WORDS LIE AT THE CROSSROADS, THE FOUNTAIN AND THE "+D$(3 TO ): RETURN
funct_3310()
 X=INT ((ROOMID-1)/2)+1
 RESTORE X*10+3620
 FOR I=0 TO ROOMID-X*2+1
 READ D$: NEXT I
 RETURN
funct_3330()
 RESTORE 4030
 RETURN
funct_3350()
 O$=O$(2 TO ): RETURN
funct_3360()
 PRINT "PRESS ENTER TO CONTINUE"
 INPUT Z$: RETURN
funct_3380()
 DIM OBJLOC(TOBJCOUNT): DIM E$(ROOMCOUNT,4): DIM FLAGS(70): DIM X$(6,4): DIM Y$(6,7): DIM G$(2,8): DIM X(VERBCOUNT+1)
 GOSUB funct_3330
 FOR I=1 TO OBJCOUNT: READ T$: NEXT I
 FOR I=1 TO 6: READ X$(I),Y$(I): NEXT I
 VERBS$="NOOEOOSOOWOOUOODOOINVGETTAKEXAREAGIVSAYPICWEATIECLIRIGUSEOPE"
 VERBS$=VERBS$+"LIGFILPLAWATSWIEMPENTCROREMFEETURDIVBAILEATHRINSBLODROEATMOV"
 VERBS$=VERBS$+"INTRINCUTHOLBURPOISHOUNLWITDRICOUPAYMAKBRESTEGATREF"
 GOSUB funct_5000
 GOSUB funct_4400: PRINT "DO YOU WANT TO"
 PRINT : PRINT " 1. START A NEW GAME"
 PRINT "OR 2. CONTINUE A SAVED GAME"
funct_3580()
 PRINT : PRINT : PRINT "TYPE IN EITHER 1 OR 2"
 INPUT C: IF C<>1 AND C<>2 THEN GOTO funct_3580
 IF C=1 THEN GOSUB funct_4450
 IF C=2 THEN GOSUB funct_4600
 RETURN
 DATA "11HALF-DUG GRAVE","12GOBLIN GRAVEYARD"
 DATA "11HOLLOW TOMB","23STALACTITES AND STALAGMITES"
 DATA "11MAZE OF TUNNELS","11VAULTED CAVERN"
 DATA "23HIGH GLASS GATES","12ENTRANCE HALL TO THE PALACE"
 DATA "31GRARG SENTRY POST","12GUARD ROOM"
 DATA "31MARSHY INLET","23RUSTY GATES"
 DATA "12GAMEKEEPER'S COTTAGE","31MISTY POOL"
 DATA "11HIGH-WALLED GARDEN","14INSCRIBED CAVERN"
 DATA "34ORNATE FOUNTIAN","11DANK CORRIDOR"
 DATA "12LONG GALLERY","12KITCHENS OF THE PALACE"
 DATA "34OLD KILN","44OVERGROWN TRACK"
 DATA "31DISUSED WATERWHEEL","33SLUICE GATES"
 DATA "11GAP BETWEEN SOME BOULDERS","41PERILOUS PATH"
 DATA "31SILVER BELL IN THE ROCK","12DUNGEONS OF THE PALACE"
 DATA "11BANQUETING HALL","42PALACE BATTLEMENTS"
 DATA "44ISLAND SHORE","31BEACHED KETCH"
 DATA "13BARREN COUNTRYSIDE","33SACKS ON THE UPPER FLOOR"
 DATA "46FROZEN POND","21MOUNTAIN HUT"
 DATA "31ROW OF CASKS","11WINE CELLAR"
 DATA "12HALL OF TAPESTRIES","11DUSTY LIBRARY"
 DATA "13ROUGH WATER","11PLOUGHED FIELD"
 DATA "55OUTSIDE A WINDMILL","42LOWER FLOOR OF THE MILL"
 DATA "44ICY PATH","41SCREE SLOPE"
 DATA "12SILVER CHAMBER","12WIZARD'S LAIR"
 DATA "11MOSAIC-FLOORED HALL","12SILVER THRONE ROOM"
 DATA "12MIDDLE OF THE LAKE","42EDGE OF AN ICY LAKE"
 DATA "41PITTED TRACK","41HIGH PINNACLE"
 DATA "55ABOVE A GLACIER","21 HUGE FALLEN OAK"
 DATA "11TURRET ROOM WITH A SLOT MACHINE","11COBWEBBY ROOM"
 DATA "31SAFE IN OGBAN'S CHAMBER","31CUPBOARD IN A CORNER"
 DATA "11NARROW PASSAGE","16CAVE"
 DATA "11WOODMAN'S HUT","42SIDE OF A WOODED VALLEY"
 DATA "21STREAM IN A VALLEY BOTTOM","11DEEP DARK WOOD"
 DATA "11SHADY HOLLOW","34ANCIENT STONE CIRCLE"
 DATA "16STABLE","14ATTIC BEDROOM"
 DATA "11DAMP WELL BOTTOM","32TOP OF A DEEP WELL"
 DATA "31BURNT-OUT CAMPFIRE","16ORCHARD"
 DATA "62END OF A BRIDGE","62END OF A BRIDGE"
 DATA "61CROSSROADS","41WINDING ROAD"
 DATA "11VILLAGE OF RUSTIC HOUSES","11WHITE COTTAGE"
 DATA "3COINS","1SHEET","3BOOTS","1HORSESHOE","3APPLES","1BUCKET","4AXE","1BOAT","1PHIAL"
 DATA "3REEDS","1BONE","1SHIELD","3PLANKS","1ROPE","1RING","1JUG","1NET","1SWORD"
 DATA "1SILVER PLATE","1UNIFORM","1KEY","3SEEDS","1LAMP","3BREAD","1BROOCH","3MATCHES"
 DATA "2STONE OF DESTINY","4APPLE","BED","CUPBOARD","BRIDGE","TREES","SAIL","KILN"
 DATA "KETCH","BRICKS","WINDMILL","SACKS","OGBAN'S BOAR","WHEEL"
 DATA "PONY","GRAVESTONES","POOL","GATES","HANDLE","HUT","VINE","INSCRIPTIONS","TROLL","RUBBLE"
 DATA "HOUND","FOUNTAIN","CIRCLE","MOSAICS","BOOKS","CASKS","WELL","WALLS","RATS","SAFE"
 DATA "COBWEBS","COIN","BELL","UP SILVER PLATE","STONES","KITCHENS","GOBLET","WINE"
 DATA "GRARGS","DOOR","AWAKE","GUIDE","PROTECT","LEAD","HELP","CHEST","WATER"
 DATA "STABLES","SLUICE GATES","POT","STATUE","PINNACLE","MUSIC","MAGIC WORDS"
 DATA "MISTY POOL","WELL BOTTOM","OLD KILN","MOUNTIAN HUT"
 DATA "IN","A","NEAR","THE","BY","SOME","ON","AN","","","AT","A SMALL"
 DATA "E","ESW","WE","EW","EW","ESW","ESW","ES","EW","SW"
 DATA "S","N","ES","SW","S","NW","N","N","ES","NSW"
 DATA "NS","E","NSW","N","NES","EW","W","S","NS","N"
 DATA "NES","W","NS","D","NES","SW","E","NW","NS","S"
 DATA "NS","E","NSEW","WU","UD","NS","E","SW","NSE","NW"
 DATA "NE","EW","NSW","E","WN","S","E","NEW","NW","S"
 DATA "ES","SW","NES","EW","SW","NE","EW","ESW","SW","ND"
 DATA ".","E","NEW","EW","NEW","EW","EW","NEW","NEW","WU"
 DATA 80,70,60,69,74,72,63,52,20,11,1,14,36,54,61,21,32,10,50
 DATA 29,59,34,13,80,30,81,47,74
 DATA 1,2,3,4,5,9,12,13,16,17,20,21,22
 Z$="": FOR I=1 TO LEN(R$)
 C$=R$(I): IF C$<"A" THEN Z$=Z$+C$: GOTO funct_4300
 C=CODE (C$)-1: IF C=64 THEN C=90
 Z$=Z$+CHR$ (C)
funct_4300()
 NEXT I: R$=Z$: RETURN
funct_4310()
 J$="SSSSSSSS": NG=0
funct_4320()
 MP=DIRID/2: GOSUB funct_4400
 PRINT "YOU ARE LOST IN THE": PRINT " TUNNELS"
 PRINT "WHICH WAY? (N,S,E,W)"
 IF NG>15 THEN PRINT "(OR G TO GIVE UP!)"
 PRINT : INPUT W$: J$=(J$+W$(1))(2 TO )
 IF W$="G" THEN FLAGS(56)=1: RETURN
 IF J$<>G$(MP) THEN NG=NG+1: GOTO funct_4320
 RETURN
funct_4400()
 CLS : PRINT
 PRINT TAB (SCREENWIDTH/2-9);"MYSTERY OF SILVER"
 PRINT TAB (SCREENWIDTH/2-9);" MOUNTAIN"
 PRINT "================================"
 PRINT : PRINT : RETURN
funct_4450()
 FOR I=1 TO ROOMCOUNT: READ E$(I): NEXT I
 FOR I=1 TO TOBJCOUNT: READ OBJLOC(I): NEXT I
 FOR I=1 TO 13: READ A: FLAGS(A)=1: NEXT I
 FLAGS(41)=INT (RND*900)+100: FLAGS(42)=INT (RND*3)+2
 FLAGS(44)=4: FLAGS(57)=68: FLAGS(58)=54: FLAGS(59)=15: FLAGS(52)=INT (RND*3)
 ROOMID=ROOM_CROSSROADS: R$="GOOD LUCK ON YOUR QUEST!"
 G$(1)="": FOR I=1 TO 8
 F$=VERBS$(1+INT (RND*4)*3)
 G$(1)=G$(1)( TO I-1)+F$
 IF F$="N" THEN L$="S"
 IF F$="S" THEN L$="N"
 IF F$="E" THEN L$="W"
 IF F$="W" THEN L$="E"
 G$(2)=L$+G$(2)( TO I-1)
 NEXT I: RETURN
funct_4600()
 GOSUB funct_4640: GOSUB funct_4670
 ROOMID=FLAGS(69): R$="OK. CARRY ON"
 RETURN
funct_4630()
 FLAGS(69)=ROOMID: GOSUB funct_4640: GOSUB funct_4760: PRINT "BYE...": STOP
funct_4640()
 PRINT : PRINT "ENTER FILE NAME": INPUT F$
 RETURN
 REM READ DATA FILE
funct_4670()
 REM
 PRINT "OK.SEARCHING FOR ";F$
 LOAD F$+"(E$)" DATA E$()
 LOAD F$+"(C)" DATA OBJLOC()
 LOAD F$+"(F)" DATA FLAGS()
 LOAD F$+"(G$)" DATA G$()
 RETURN
 REM SAVE DATA FILE
funct_4760()
 REM
 SAVE F$+"(E$)" DATA E$()
 SAVE F$+"(C)" DATA OBJLOC()
 SAVE F$+"(F)" DATA FLAGS()
 SAVE F$+"(G$)" DATA G$()
 RETURN
funct_4830()
 LS=1: LP=1
 FOR I=1 TO LEN(J$)
 IF J$(I)=" " AND LL>SCREENWIDTH THEN PRINT J$(LP TO LS-1): LL=I-LS: LP=LS+1
 IF J$(I)=" " THEN LS=I
 LL=LL+1: NEXT I
 PRINT J$(LP TO );
 RETURN
funct_4900()
 P$=Y$(VAL (O$(1))): GOSUB funct_3350
funct_4910()
 IF P$(LEN(P$))=" " THEN P$=P$( TO LEN(P$)-1): GOTO funct_4910
 J$=J$+" "+P$+" "+O$+","
 RETURN
funct_5000()
 RESTORE 6000: FOR I=1 TO VERBCOUNT+1
 READ X(I): NEXT I
 RESTORE 4150: RETURN
 DATA 800,800,800,800,800,800,1220,1290,1290,1470,1470,1750,1890
 DATA 1960,1980,2010,2050,2870,2120,2220,2310,2380,2420,2450,2470,2520
 DATA 2550,2580,2610,2650,2670,2700,2720,2730,2830,2800,2870,2730,2920
 DATA 2950,2990,3010,3050,3070,2310,2990,3070,3130,2120,3190,1470,3100
 DATA 2870,3150,1290,1290,3170,3200 