 SCREENWIDTH=32; OBJCOUNT=88; VERBCOUNT=57; TOBJCOUNT=28; ROOMCOUNT=80
 funct_3380()
funct_30()
 funct_4400()
 LL=0
 funct_3310()
 P$=X$(VAL (D$(1)))
 if(P$(1)==" ")
 { P$=""; GOTO funct_69;}
funct_63()
 if(P$(LEN(P$))==" ")
 { P$=P$( TO LEN(P$)-1); GOTO funct_63;}
 P$=P$+" "+Y$(VAL (D$(2)))
funct_68()
 if(P$(LEN(P$))==" ")
 { P$=P$( TO LEN(P$)-1); GOTO funct_68;}
funct_69()
 P$=P$+" "
 J$=R$+". "+"YOU ARE "+P$+D$(3 TO )+" "; funct_4830()
 funct_3330(); J$=""
 FOR I=1 TO TOBJCOUNT-1
 READ O$
 if(FLAGS[I]==0  &&  OBJLOC[I]==ROOMID)
 { funct_4900();}
 NEXT I
 if(ROOMID==ROOM_BANQUETING_HALL  &&  FLAGS[48]==0)
 { J$=J$+" GRARGS FEASTING,";}
 if(ROOMID==ROOM_BANQUETING_HALL  &&  FLAGS[48]==1)
 { J$=J$+" A SLEEPING GRARG,";}
 if(ROOMID==ROOM_RUSTY_GATES  ||  ROOMID==ROOM_OVERGROWN_TRACK)
 { J$=J$+" A PONY,";}
 if(ROOMID==ROOM_SIDE_OF_A_WOODED_VALLEY)
 { J$=J$+" A HERMIT,";}
 if(ROOMID==ROOM_DANK_CORRIDOR  &&  E$(18)=="N ")
 { J$=J$+" AN OAK DOOR,";}
 if(ROOMID==ROOM_SAFE_IN_OGBANS_CHAMBER  &&  FLAGS[68]==1)
 { J$=J$+" OGBAN (DEAD),";}
 if(J$!=="")
 { J$=", YOU CAN SEE"+J$;}
 J$=J$+" AND YOU CAN GO "
 funct_4830(); PRINT(" ");
 FOR I=1 TO LEN(E$(ROOMID)); if(E$(ROOMID,I)!==" ")
 { PRINT(E$(ROOMID,I),",");;}
 NEXT I; PRINT(); ; PRINT();
 strcpy(szMSG,"PARDON?");; PRINT( "================================");
 PRINT(); ; PRINT(); ; PRINT( "WHAT WILL YOU DO NOW");
 INPUT I$
 if(I$=="SAVE GAME")
 { GOTO funct_4630;}
 V$=""; T$=""; VERBID=0; OBJID=0
 FOR I=1 TO LEN(I$)-1
 if(I$(I)==" "  &&  V$=="")
 { V$=I$( TO I-1);}
 if(I$(I+1)!==" "  &&  V$!=="")
 { T$=I$(I+1 TO ); I=LEN(I$);}
 NEXT I; if(T$=="")
 { V$=I$;}
funct_340()
 if(LEN(V$)<3)
 { V$=V$+"O"; GOTO funct_340;}
 if(V$=="PLAY")
 { V$="BLO";}
 U$=V$( TO 3)
 FOR I=1 TO VERBCOUNT; if(VERBS$(I*3-2 TO I*3)==U$)
 { VERBID=I; I=VERBCOUNT;}
 NEXT I; FLAGS[36]=0
funct_390()
 funct_3330()
 FOR I=1 TO OBJCOUNT; READ O$; if(I<==TOBJCOUNT)
 { funct_3350();}
 if(T$==O$)
 { OBJID=I; I=OBJCOUNT;}
 NEXT I
 if(OBJID==0  &&  FLAGS[36]==0  &&  T$>"")
 { T$=T$+"S"; FLAGS[36]=1; GOTO funct_390;}
 if(VERBID==0)
 { VERBID=VERBCOUNT+1;}
 if(T$=="")
 { strcpy(szMSG,"I NEED TWO WORDS");;}
 if(VERBID>VERBCOUNT)
 { strcpy(szMSG,"TRY SOMETHING ELSE");;}
 if(VERBID>VERBCOUNT  &&  OBJID==0)
 { strcpy(szMSG,"YOU CANNOT ");+I$;}
 if(OBJID>TOBJCOUNT  ||  OBJID==0)
 { GOTO funct_510;}
 if(VERBID==VERB_GET  ||  VERBID==VERB_TAKE  ||  VERBID==VERB_PICK  ||  VERBID==VERB_CLIMB  ||  VERBID==VERB_HOLD  ||  VERBID>VERB_BREAK)
 { GOTO funct_510;}
 if(VERBID<VERBCOUNT  &&  OBJLOC[OBJID]!==0)
 { strcpy(szMSG,"YOU DO NOT HAVE THE ");+T$; GOTO funct_30;}
funct_510()
 if(ROOMID==ROOM_HUGE_FALLEN_OAK  &&  FLAGS[35]==0  &&  VERBID!==VERB_BLOW  &&  VERBID!==VERB_MAKE)
 { strcpy(szMSG,"THE GHOST OF THE GOBLIN GUARDIAN");+" HAS GOT YOU!"; GOTO funct_30;}
 if(VERBID==VERB_HOLD  ||  VERBID==VERB_SHOW  ||  VERBID==VERB_USE  ||  VERBID==VERB_REFLECT  ||  VERBID==VERB_WITH)
 { GOTO funct_540;}
 if(ROOMID==ROOM_WIZARDS_LAIR  &&  FLAGS[63]==0)
 { strcpy(szMSG,"THE WIZARD HAS YOU IN HIS GLARE");; GOTO funct_30;}
funct_540()
 H=VAL (STR$ (ROOMID)+STR$ (OBJID))
 X()(VERBID)
 GOTO funct_650
funct_650()
 if(FLAGS[62]==1)
 { GOTO funct_730;}
 if(ROOMID==ROOM_ROUGH_WATER)
 { FLAGS[67]=FLAGS[67]+1; if(FLAGS[67]==10)
 { FLAGS[56]=1; strcpy(szMSG,"YOU SANK!");;};}
 if(ROOMID==ROOM_HUGE_FALLEN_OAK  &&  FLAGS[35]==0  &&  OBJLOC[OBJ_REEDS]!==0)
 { strcpy(szMSG,"THE GHOST OF THE GOBLIN GUARDIAN");+" GETS YOU!"; FLAGS[56]=1;}
 if(FLAGS[56]==0)
 { GOTO funct_30;}
 funct_4400(); PRINT(R$);
 PRINT( "YOU HAVE FAILED IN YOUR QUEST!");
 PRINT(); ; PRINT("BUT YOU ARE GRANTED ANOTHER TRY");
 funct_3360(); RUN
funct_730()
 funct_4400()
 PRINT( "HOOORRRRAAAYYYY!");
 PRINT();
 PRINT("YOU HAVE SUCCEEDED IN YOUR");
 PRINT("QUEST AND BROUGHT PEACE TO");
 PRINT("THE LAND");
 STOP
void c_FUNCT_MOVE()
{
 DIRID=VERBID
 if(DIRID==VERB_UP)
 { DIRID=VERB_NORTH;}
 if(DIRID==VERB_DOWN)
 { DIRID=VERB_SOUTH;}
 if(NOT ((ROOMID==ROOM_WEST_END_OF_A_BRIDGE  &&  DIRID==VERB_EAST)  ||  (ROOMID==ROOM_EAST_END_OF_A_BRIDGE  &&  DIRID==VERB_WEST))  ||  FLAGS[64]==1)
 { GOTO funct_850;}
 strcpy(szMSG,"A TROLL STOPS YOU CROSSING");; ; return;
funct_850()
 if(FLAGS[64]==1)
 { FLAGS[64]=0;}
 if(FLAGS[51]==1  ||  FLAGS[29]==1)
 { GOTO funct_900;}
 if(FLAGS[55]==1)
 { FLAGS[56]=1; strcpy(szMSG,"GRARGS HAVE GOT YOU!");; return;;}
 if(ROOMID==ROOM_BANQUETING_HALL  &&  FLAGS[48]==0)
 { strcpy(szMSG,"GRARGS WILL SEE YOU!");; return;;}
 if(ROOMID==ROOM_BURNTOUT_CAMPFIRE  ||  ROOMID==ROOM_PLOUGHED_FIELD  ||  ROOMID==ROOM_GRARG_SENTRY_POST  ||  ROOMID==ROOM_GUARD_ROOM)
 { strcpy(szMSG,"A GRARG PATROL APPROACHES");; FLAGS[55]=1; return;;}
funct_900()
 if(OBJLOC[OBJ_BOAT]==ROOM_INVENTORY  &&  ((ROOMID==ROOM_EDGE_OF_AN_ICY_LAKE  &&  DIRID==VERB_EAST)  ||  (ROOMID==ROOM_ISLAND_SHORE  &&  DIRID!==VERB_SOUTH)))
 { strcpy(szMSG,"THE BOAT IS TOO HEAVY");; return;;}
 if(OBJLOC[OBJ_BOAT]!==0  &&  ((ROOMID==ROOM_EDGE_OF_AN_ICY_LAKE  &&  DIRID==VERB_WEST)  ||  (ROOMID==ROOM_ISLAND_SHORE  &&  DIRID==VERB_SOUTH)))
 { strcpy(szMSG,"YOU CANNOT SWIM");; return;;}
 if(ROOMID==ROOM_EDGE_OF_AN_ICY_LAKE  &&  OBJLOC[OBJ_BOAT]==ROOM_INVENTORY  &&  DIRID==VERB_WEST  &&  FLAGS[30]==0)
 { strcpy(szMSG,"OBJCOUNT POWER!");; return;;}
 if(ROOMID==ROOM_ROUGH_WATER  &&  DIRID==VERB_SOUTH  &&  FLAGS[31]==0)
 { strcpy(szMSG,"THE BOAT IS SINKING!");; ; return;;}
 if(ROOMID==ROOM_BARREN_COUNTRYSIDE  &&  DIRID==VERB_NORTH  &&  FLAGS[32]==0)
 { strcpy(szMSG,"OGBAN'S BOAR BLOCKS YOUR PATH");; return;;}
 if(((ROOMID==ROOM_HOLLOW_TOMB  &&  DIRID==VERB_EAST)  ||  (ROOMID==ROOM_STALACTITES_AND_STALAGMITES  &&  DIRID==VERB_WEST))  &&  FLAGS[45]==0)
 { strcpy(szMSG,"A PILE OF RUBBLE BLOCKS YOUR PATH");; return;;}
 if(ROOMID==ROOM_6FROZEN_POND  &&  OBJLOC[OBJ_PLANKS]!==ROOMID)
 { strcpy(szMSG,"THE ICE IS BREAKING!");; return;;}
 if(ROOMID==ROOM_MAZE_OF_TUNNELS  &&  (DIRID==VERB_EAST  ||  DIRID==VERB_WEST))
 { funct_4310();}
 if(ROOMID==ROOM_STALACTITES_AND_STALAGMITES  &&  DIRID==VERB_WEST)
 { strcpy(szMSG,"PASSAGE IS TOO STEEP");; return;;}
 if(ROOMID==ROOM_HIGH_GLASS_GATES  &&  DIRID==VERB_EAST  &&  FLAGS[46]==0)
 { strcpy(szMSG,"A HUGE HOUND BARS YOUR WAY");; return;;}
 if((ROOMID==ROOM_WINE_CELLAR  ||  ROOMID==ROOM_ROW_OF_CASKS)  &&  FLAGS[50]==0)
 { strcpy(szMSG,"IT IS TOO DARK");; ; return;;}
 if(ROOMID==ROOM_MOSAICFLOORED_HALL  &&  DIRID==VERB_EAST  &&  FLAGS[54]==0)
 { strcpy(szMSG,"MYSTERIOUS FORCES HOLD YOU BACK");; return;;}
 if(ROOMID==ROOM_MOSAICFLOORED_HALL  &&  DIRID==VERB_SOUTH  &&  FLAGS[68]==0)
 { strcpy(szMSG,"YOU MET OGBAN!!!");; FLAGS[56]=1; return;;}
 if(ROOMID==ROOM_WINE_CELLAR  &&  FLAGS[65]==0)
 { strcpy(szMSG,"RATS NIBBLE YOUR ANKLES");; return;;}
 if(ROOMID==ROOM_COBWEBBY_ROOM  &&  (DIRID==VERB_NORTH  ||  DIRID==VERB_WEST)  &&  FLAGS[66]==0)
 { strcpy(szMSG,"YOU GET CAUGHT IN THE COBWEBS!");; return;;}
 if(ROOMID==ROOM_WIZARDS_LAIR  &&  DIRID==VERB_WEST  &&  FLAGS[70]==0)
 { strcpy(szMSG,"THE DOOR DOES NOT OPEN");; return;;}
 if(ROOMID==ROOM_DUSTY_LIBRARY  &&  FLAGS[47]==1)
 { FLAGS[68]=1;}
 if(ROOMID==ROOM_ROW_OF_CASKS  &&  DIRID==VERB_WEST  &&  E$(37)=="EW ")
 { ROOMID=ROOM_SHADY_HOLLOW; strcpy(szMSG,"THE PASSAGE WAS STEEP!");; return;;}
 if(ROOMID==ROOM_BANQUETING_HALL  &&  DIRID==VERB_SOUTH)
 { FLAGS[48]=1; FLAGS[OBJ_UNIFORM]=OBJ_STATUS_VISIBLE;}
 if(ROOMID==ROOM_ENTRANCE_HALL_TO_THE_PALACE  &&  DIRID==VERB_EAST)
 { FLAGS[46]=0;}
 OM=ROOMID; FOR I=1 TO LEN(E$(ROOMID))
 K$=E$(OM,I)
 if((K$=="N"  ||  K$=="U")  &&  DIRID==VERB_NORTH)
 { ROOMID=ROOMID-10;}
 if(K$=="E"  &&  DIRID==VERB_EAST)
 { ROOMID=ROOMID+1;}
 if((K$=="S"  ||  K$=="D")  &&  DIRID==VERB_SOUTH)
 { ROOMID=ROOMID+10;}
 if(K$=="W"  &&  DIRID==VERB_WEST)
 { ROOMID=ROOMID-1;}
 NEXT I; strcpy(szMSG,"OK");
 if(ROOMID==OM)
 { strcpy(szMSG,"YOU CANNOT GO THAT WAY");;}
 if(((OM==75  &&  DIRID==VERB_EAST)  ||  (OM==76  &&  DIRID==VERB_WEST)))
 { strcpy(szMSG,"OK. YOU CROSSED");;}
 if(FLAGS[29]==1)
 { FLAGS[39]=FLAGS[39]+1;}
 if(FLAGS[39]>5  &&  FLAGS[29]==1)
 { strcpy(szMSG,"BOOTS HAVE WORN OUT");; ; FLAGS[29]=0; OBJLOC[OBJ_BOOTS]=ROOM_NOWHERE;}
}
void c_FUNCT_INVENTORY()
{
 funct_3330(); strcpy(szMSG,"OK");; FLAGS[49]=0
 PRINT("YOU HAVE ");
 FOR I=1 TO TOBJCOUNT; READ O$; funct_3350(); if(I==1  &&  OBJLOC[OBJ_COINS]==ROOM_INVENTORY  &&  FLAGS[44]==1)
 { O$="COIN";}
 if(I==TOBJCOUNT  &&  OBJLOC[OBJ_APPLES]==ROOM_INVENTORY)
 { GOTO funct_1270;}
 if(OBJLOC[I]==ROOM_INVENTORY)
 { PRINT(O$,",");; FLAGS[49]=1;}
funct_1270()
 NEXT I; if(FLAGS[49]==0)
 { PRINT("NOTHING");;}
 PRINT(); ; funct_3360(); return;
void c_FUNCT_GET()
{
 if(((ROOMID==ROOM_STREAM_IN_A_VALLEY_BOTTOM) && (OBJID==OBJ_WATER)))
 { strcpy(szMSG,"HOW?");; return;;}
 if(((ROOMID==ROOM_ROUGH_WATER) && (OBJID==OBJ_WATER))  ||  ((ROOMID==ROOM_MIDDLE_OF_THE_LAKE) && (OBJID==OBJ_WATER)))
 { OBJID=OBJ_JUG; FUNCT_FILL(); return;;}
 if(OBJID==OBJ_SACKS)
 { strcpy(szMSG,"TOO HEAVY!");; return;;}
 if(OBJID==OBJ_HORSESHOE  &&  FLAGS[43]==0)
 { strcpy(szMSG,"IT IS FIRMLY NAILED ON!");; return;;}
 CO=0; FOR I=1 TO TOBJCOUNT-1; if(OBJLOC[I]==ROOM_INVENTORY)
 { CO=CO+1;}
 NEXT I; if(CO>13)
 { strcpy(szMSG,"YOU CANNOT CARRY ANY MORE");; return;;}
 if(OBJID>TOBJCOUNT)
 { strcpy(szMSG,"YOU CANNOT GET THE ");+T$; return;;}
 if(OBJID==0)
 { return;;}
 if(OBJLOC[OBJID]!==ROOMID)
 { strcpy(szMSG,"IT IS NOT HERE!");;}
 if(FLAGS[OBJID]==1)
 { strcpy(szMSG,"WHAT ");+T$+"?";}
 if(OBJLOC[OBJID]==ROOM_INVENTORY)
 { strcpy(szMSG,"YOU ALREADY HAVE IT");;}
 if(OBJLOC[OBJID]==ROOMID  &&  FLAGS[OBJID]==0)
 { OBJLOC[OBJID]=ROOM_INVENTORY; strcpy(szMSG,"YOU HAVE THE ");+T$;}
 if(OBJID==OBJ_APPLE)
 { OBJLOC[OBJ_APPLES]=ROOM_NOWHERE;}
 if(OBJID==OBJ_APPLES)
 { OBJLOC[OBJ_APPLE]=ROOM_INVENTORY;}
 if(OBJLOC[OBJ_HORSESHOE]==ROOM_INVENTORY  &&  OBJLOC[OBJ_SHIELD]==ROOM_INVENTORY  &&  OBJLOC[OBJ_RING]==ROOM_INVENTORY)
 { FLAGS[54]=1;}
 if(OBJID==OBJ_BOAT  &&  FLAGS[30]==1)
 { OBJLOC[OBJ_SHEET]=ROOM_INVENTORY;}
 if(OBJID==OBJ_SHEET)
 { FLAGS[30]=0;}
}
void c_FUNCT_EXAMINE()
{
 strcpy(szMSG,"YOU SEE WHAT YOU MIGHT EXPECT!");
 if(OBJID>0)
 { strcpy(szMSG,"NOTHING SPECIAL");;}
 if(OBJID==OBJ_HUT  ||  OBJID==OBJ_MOUNTIAN_HUT)
 { FUNCT_ENTER();}
 if(((ROOMID==ROOM_WHITE_COTTAGE) && (OBJID==OBJ_CHEST)))
 { strcpy(szMSG,"IT IS EMPTY");;}
 if(((ROOMID==ROOM_WHITE_COTTAGE) && (OBJID==OBJ_POT)))
 { strcpy(szMSG,"AHA!");; FLAGS[OBJ_COINS]=OBJ_STATUS_VISIBLE;}
 if(((ROOMID==ROOM_ATTIC_BEDROOM) && (OBJID==OBJ_BED)))
 { strcpy(szMSG,"OK");; FLAGS[OBJ_SHEET]=OBJ_STATUS_VISIBLE;}
 if(OBJID==OBJ_UNIFORM)
 { strcpy(szMSG,"MATCHES IN POCKET");; ; OBJLOC[OBJ_MATCHES]=ROOM_INVENTORY;}
 if(((ROOMID==ROOM_INSCRIBED_CAVERN) && (OBJID==OBJ_INSCRIPTIONS)))
 { strcpy(szMSG,"THERE ARE SOME LETTERS '");+G$(2)+"'";}
 if(((ROOMID==ROOM_ORCHARD) && (OBJID==OBJ_TREES)))
 { strcpy(szMSG,"THEY ARE APPLE TREES");; ; FLAGS[OBJ_APPLES]=OBJ_STATUS_VISIBLE;}
 if(((ROOMID==ROOM_OLD_KILN) && (OBJID==OBJ_KILN))  ||  ((ROOMID==ROOM_OLD_KILN) && (OBJID==OBJ_OLD_KILN)))
 { strcpy(szMSG,"OK");; FLAGS[OBJ_JUG]=OBJ_STATUS_VISIBLE;}
 if(OBJID==OBJ_KETCH)
 { strcpy(szMSG,"IT IS FISHY!");; FLAGS[OBJ_NET]=OBJ_STATUS_VISIBLE;}
 if(((ROOMID==ROOM_SACKS_ON_THE_UPPER_FLOOR) && (OBJID==OBJ_SACKS)))
 { strcpy(szMSG,"OK");; FLAGS[OBJ_SEEDS]=OBJ_STATUS_VISIBLE;}
 if(((ROOMID==ROOM_GOBLIN_GRAVEYARD) && (OBJID==OBJ_GRAVESTONES)))
 { strcpy(szMSG,"A FADED INSCRIPTION");;}
 if((((ROOMID==ROOM_MISTY_POOL) && (OBJID==OBJ_POOL))  ||  ((ROOMID==ROOM_MISTY_POOL) && (OBJID==OBJ_MISTY_POOL)))  &&  FLAGS[33]==0)
 { strcpy(szMSG,"A GLIMMERING FROM THE DEPTHS");; ;}
 if((((ROOMID==ROOM_MISTY_POOL) && (OBJID==OBJ_POOL))  ||  ((ROOMID==ROOM_MISTY_POOL) && (OBJID==OBJ_MISTY_POOL)))  &&  FLAGS[33]==1)
 { strcpy(szMSG,"SOMETHING HERE....");; FLAGS[OBJ_SHIELD]=OBJ_STATUS_VISIBLE;}
 if(((ROOMID==ROOM_SLUICE_GATES) && (OBJID==OBJ_SLUICE_GATES))  ||  ((ROOMID==ROOM_SLUICE_GATES) && (OBJID==OBJ_GATES)))
 { strcpy(szMSG,"THERE IS A HANDLE");;}
 if(OBJID==OBJ_PHIAL)
 { strcpy(szMSG,"THE LABEL READS 'POISON'");; ;}
 if(((ROOMID==ROOM_DUSTY_LIBRARY) && (OBJID==OBJ_BOOKS)))
 { funct_3290();}
 if(((ROOMID==ROOM_BANQUETING_HALL) && (OBJID==OBJ_GRARGS))  &&  FLAGS[48]==1)
 { strcpy(szMSG,"VERY UGLY!");;}
 if(((ROOMID==ROOM_DAMP_WELL_BOTTOM) && (OBJID==OBJ_WALLS))  ||  ((ROOMID==ROOM_DAMP_WELL_BOTTOM) && (OBJID==OBJ_WELL_BOTTOM)))
 { strcpy(szMSG,"THERE ARE LOOSE BRICKS");;}
 if(ROOMID==ROOM_MOSAICFLOORED_HALL)
 { strcpy(szMSG,"VERY INTERSTING!");;}
 if(OBJID==OBJ_FOUNTAIN  ||  OBJID==OBJ_PINNACLE  ||  OBJID==OBJ_STATUE)
 { strcpy(szMSG,"INTERESTING!");;}
 if(((ROOMID==ROOM_STABLE) && (OBJID==OBJ_STABLES)))
 { strcpy(szMSG,"THERE IS A WOODEN DOOR");;}
 if(((ROOMID==ROOM_STABLE) && (OBJID==OBJ_DOOR)))
 { strcpy(szMSG,"YOU FOUND SOMETHING");; FLAGS[OBJ_HORSESHOE]=OBJ_STATUS_VISIBLE;}
 if(((ROOMID==ROOM_KITCHENS_OF_THE_PALACE) && (OBJID==OBJ_KITCHENS)))
 { strcpy(szMSG,"A LARGE CUPBOARD IN THE CORNER");;}
 if(((ROOMID==ROOM_ANCIENT_STONE_CIRCLE) && (OBJID==OBJ_STONES))  ||  ((ROOMID==ROOM_ANCIENT_STONE_CIRCLE) && (OBJID==OBJ_CIRCLE)))
 { strcpy(szMSG,"THERE ARE NINE STONES");;}
 if(((ROOMID==ROOM_GOBLIN_GRAVEYARD) && (OBJID==OBJ_INSCRIPTIONS)))
 { strcpy(szMSG,"A FADED WORD - 'M R H S'");; ;}
}
void c_FUNCT_GIVE()
{
 if(ROOMID==ROOM_SIDE_OF_A_WOODED_VALLEY)
 { strcpy(szMSG,"HE GIVES IT BACK!");;}
 if(((ROOMID==ROOM_SIDE_OF_A_WOODED_VALLEY) && (OBJID==OBJ_BROOCH)))
 { funct_3210();}
 if(ROOMID==ROOM_WEST_END_OF_A_BRIDGE  ||  ROOMID==ROOM_EAST_END_OF_A_BRIDGE)
 { strcpy(szMSG,"HE DOES NOT WANT IT");;}
 if(OBJID==OBJ_COIN  &&  FLAGS[44]==0)
 { strcpy(szMSG,"YOU HAVE RUN OUT!");;}
 if((((ROOMID==ROOM_WEST_END_OF_A_BRIDGE) && (OBJID==OBJ_COIN))  ||  ((ROOMID==ROOM_EAST_END_OF_A_BRIDGE) && (OBJID==OBJ_COIN)))  &&  FLAGS[44]>0  &&  OBJLOC[OBJ_COINS]==ROOM_INVENTORY)
 { strcpy(szMSG,"HE TAKES IT");; FLAGS[64]=1;}
 if(FLAGS[64]==1)
 { FLAGS[44]=FLAGS[44]-1; if(FLAGS[44]==0)
 { OBJLOC[OBJ_COINS]=ROOM_NOWHERE;};}
 if(OBJID==OBJ_COINS)
 { strcpy(szMSG,"HE TAKES THEM ALL!");; OBJLOC[OBJ_COINS]=ROOM_NOWHERE; FLAGS[64]=1; FLAGS[44]=0;}
 if(((ROOMID==ROOM_OVERGROWN_TRACK) && (OBJID==OBJ_APPLE))  &&  OBJLOC[OBJ_APPLES]==ROOM_NOWHERE)
 { strcpy(szMSG,"HE LEADS YOU ");+"NORTH"; OBJLOC[OBJ_APPLE]=ROOM_NOWHERE; ROOMID=ROOM_RUSTY_GATES;}
 if((((ROOMID==ROOM_OVERGROWN_TRACK) && (OBJID==OBJ_APPLE))  &&  OBJLOC[OBJ_APPLES]==ROOM_INVENTORY)  ||  ((ROOMID==ROOM_OVERGROWN_TRACK) && (OBJID==OBJ_APPLES)))
 { strcpy(szMSG,"HE LEADS YOU ");+"NORTH"; ROOMID=ROOM_RUSTY_GATES;}
 if((((ROOMID==ROOM_RUSTY_GATES) && (OBJID==OBJ_APPLE))  &&  OBJLOC[OBJ_APPLES]==ROOM_INVENTORY)  ||  ((ROOMID==ROOM_RUSTY_GATES) && (OBJID==OBJ_APPLES)))
 { strcpy(szMSG,"HE LEADS YOU ");+"SOUTH"; ROOMID=ROOM_OVERGROWN_TRACK;}
 if(((ROOMID==ROOM_WINE_CELLAR) && (OBJID==OBJ_APPLES))  ||  ((ROOMID==ROOM_WINE_CELLAR) && (OBJID==OBJ_BREAD)))
 { strcpy(szMSG,"THEY SCURRY AWAY");; OBJLOC[OBJID]=ROOM_NOWHERE; FLAGS[65]=1;}
 if(((ROOMID==ROOM_HIGH_GLASS_GATES) && (OBJID==OBJ_BONE)))
 { FLAGS[46]=1; strcpy(szMSG,"HE IS DISTRACTED");;}
 if(OBJID==0  ||  OBJID>TOBJCOUNT)
 { return;;}
 if(ROOMID==ROOM_HIGH_GLASS_GATES  ||  ROOMID==ROOM_BARREN_COUNTRYSIDE)
 { strcpy(szMSG,"HE EATS IT!");; OBJLOC[OBJID]=ROOM_NOWHERE;}
}
void c_FUNCT_SAY()
{
 strcpy(szMSG,"YOU SAID IT");
 if(OBJID==OBJ_MAGIC_WORDS)
 { strcpy(szMSG,"YOU MUST SAY THEM ONE BY ONE!");; return;;}
 if(ROOMID!==ROOM_SILVER_CHAMBER  ||  OBJID<OBJ_AWAKE  ||  OBJID>OBJ_HELP  ||  OBJLOC[OBJ_STONE_OF_DESTINY]!==0)
 { return;;}
 if(OBJID==OBJ_AWAKE  &&  FLAGS[60]==0)
 { strcpy(szMSG,"THE MOUNTAIN RUMBLES!");; FLAGS[60]=1; return;;}
 if(OBJID==OBJ_GUIDE  &&  FLAGS[60]==1  &&  FLAGS[61]==0)
 { strcpy(szMSG,"TOWERS FALL DOWN!");; FLAGS[61]=1; return;;}
 if(OBJID==(FLAGS[52]+73)  &&  FLAGS[60]==1  &&  FLAGS[61]==1)
 { FLAGS[62]=1; return;;}
 strcpy(szMSG,"THE WRONG SACRED WORD!");; FLAGS[56]=1; return;
void c_FUNCT_PICK()
{
 if(OBJID==OBJ_APPLES  ||  OBJID==OBJ_REEDS  ||  OBJID==OBJ_APPLE)
 { FUNCT_GET();}
}
void c_FUNCT_WEAR()
{
 if(OBJID==OBJ_BOOTS)
 { FLAGS[29]=1; strcpy(szMSG,"YOU ARE INVISIBLE");; FLAGS[55]=0; ;}
 if(OBJID==OBJ_UNIFORM)
 { FLAGS[51]=1; strcpy(szMSG,"YOU ARE DISGUISED");; FLAGS[55]=0; ;}
}
void c_FUNCT_TIE()
{
 if(OBJID==OBJ_SHEET  ||  OBJID==OBJ_ROPE)
 { strcpy(szMSG,"NOTHING TO TIE IT TO!");;}
 if(((ROOMID==ROOM_TOP_OF_A_DEEP_WELL) && (OBJID==OBJ_ROPE)))
 { strcpy(szMSG,"IT IS TIED");; OBJLOC[OBJ_ROPE]=ROOM_TOP_OF_A_DEEP_WELL; FLAGS[53]=1;}
 if(((ROOMID==ROOM_TOP_OF_A_DEEP_WELL) && (OBJID==OBJ_SHEET)))
 { strcpy(szMSG,"OK");; FLAGS[40]=1; OBJLOC[OBJ_SHEET]=ROOM_TOP_OF_A_DEEP_WELL;}
}
void c_FUNCT_CLIMB()
{
 if(((ROOMID==ROOM_HIGHWALLED_GARDEN) && (OBJID==OBJ_VINE))  &&  FLAGS[38]==1)
 { strcpy(szMSG,"ALL RIGHT");; ROOMID=ROOM_INSCRIBED_CAVERN;}
 if(OBJID==OBJ_ROPE  ||  OBJID==OBJ_SHEET)
 { strcpy(szMSG,"NOT ATTACHED TO ANYTHING!");;}
 if(((ROOMID==ROOM_HIGH_PINNACLE) && (OBJID==OBJ_ROPE))  &&  OBJLOC[OBJ_ROPE]==ROOM_HIGH_PINNACLE)
 { strcpy(szMSG,"YOU ARE AT THE TOP");;}
 if(((ROOMID==ROOM_TOP_OF_A_DEEP_WELL) && (OBJID==OBJ_ROPE))  &&  FLAGS[53]==1)
 { strcpy(szMSG,"GOING DOWN");; ROOMID=ROOM_DAMP_WELL_BOTTOM;}
 if(((ROOMID==ROOM_TOP_OF_A_DEEP_WELL) && (OBJID==OBJ_SHEET))  &&  FLAGS[40]==1)
 { ROOMID=ROOM_DAMP_WELL_BOTTOM; strcpy(szMSG,"IT IS TORN");; OBJLOC[OBJ_SHEET]=ROOM_NOWHERE; FLAGS[40]=0;}
 if(((ROOMID==ROOM_DAMP_WELL_BOTTOM) && (OBJID==OBJ_ROPE))  &&  FLAGS[53]==1)
 { OBJLOC[OBJ_ROPE]=ROOM_DAMP_WELL_BOTTOM; FLAGS[53]=0; strcpy(szMSG,"IT FALLS DOWN - BUMP!");;}
}
void c_FUNCT_USE()
{
 if(((ROOMID==ROOM_EDGE_OF_AN_ICY_LAKE) && (OBJID==OBJ_SHEET)))
 { strcpy(szMSG,"OK");; FLAGS[30]=1;}
 if(OBJID==OBJ_COINS  ||  OBJID==OBJ_COIN  ||  OBJID==OBJ_APPLES  ||  OBJID==OBJ_APPLE  ||  OBJID==OBJ_BONE  ||  OBJID==OBJ_BREAD)
 { FUNCT_GIVE();}
 if(((ROOMID==ROOM_ROUGH_WATER) && (OBJID==OBJ_BUCKET)))
 { strcpy(szMSG,"YOU HAVE KEPT AFLOAT");; FLAGS[31]=1; ; return;;}
 if(((ROOMID==ROOM_ROUGH_WATER) && (OBJID==OBJ_JUG)))
 { strcpy(szMSG,"IT IS NOT BIG ENOUGH!");; return;;}
 if(OBJID==OBJ_SWORD  ||  OBJID==OBJ_AXE)
 { FUNCT_SWING();}
 if(OBJID==OBJ_PLANKS)
 { FUNCT_LEAVE();}
 if(OBJID==OBJ_SILVER_PLATE)
 { FUNCT_HOLD();}
 if(OBJID==OBJ_REEDS)
 { FUNCT_RIG();}
 if(OBJID==OBJ_JUG  ||  OBJID==OBJ_BUCKET)
 { FUNCT_FILL();}
}
void c_FUNCT_OPEN()
{
 if(OBJID==OBJ_CHEST  ||  OBJID==OBJ_SACKS)
 { FUNCT_EXAMINE();}
 if(((ROOMID==ROOM_KITCHENS_OF_THE_PALACE) && (OBJID==OBJ_CUPBOARD)))
 { FLAGS[OBJ_PHIAL]=OBJ_STATUS_VISIBLE; strcpy(szMSG,"OK");;}
 if(((ROOMID==ROOM_CUPBOARD_IN_A_CORNER) && (OBJID==OBJ_CUPBOARD)))
 { strcpy(szMSG,"OK");; FLAGS[OBJ_BOOTS]=OBJ_STATUS_VISIBLE;}
 if(((ROOMID==ROOM_SLUICE_GATES) && (OBJID==OBJ_GATES))  ||  ((ROOMID==ROOM_DANK_CORRIDOR) && (OBJID==OBJ_DOOR)))
 { strcpy(szMSG,"YOU ARE NOT STRONG ENOUGH");;}
 if(((ROOMID==ROOM_ROW_OF_CASKS) && (OBJID==OBJ_CASKS)))
 { strcpy(szMSG,"A PASSAGE!");; E$(37)="EW";}
 if(((ROOMID==ROOM_SAFE_IN_OGBANS_CHAMBER) && (OBJID==OBJ_SAFE)))
 { funct_3260();}
 if(((ROOMID==ROOM_STABLE) && (OBJID==OBJ_DOOR)))
 { strcpy(szMSG,"IT FALLS OF ITS HINGES");;}
 if(((ROOMID==ROOM_WIZARDS_LAIR) && (OBJID==OBJ_DOOR)))
 { strcpy(szMSG,"IT IS LOCKED");;}
}
void c_FUNCT_LIGHT()
{
 if(OBJID>TOBJCOUNT)
 { strcpy(szMSG,"IT DOES NOT BURN");;}
 if(OBJID==OBJ_MATCHES)
 { strcpy(szMSG,"YOU LIT THEM");;}
 if(((ROOMID==ROOM_WINE_CELLAR) && (OBJID==OBJ_MATCHES)))
 { strcpy(szMSG,"NOT BRIGHT ENOUGH");;}
 if((OBJID==OBJ_LAMP  ||  ((ROOMID==ROOM_STABLE) && (OBJID==OBJ_DOOR)))  &&  OBJLOC[OBJ_MATCHES]!==0)
 { strcpy(szMSG,"NO MATCHES");; ;}
 if(OBJID==OBJ_LAMP  &&  OBJLOC[OBJ_MATCHES]==ROOM_INVENTORY)
 { strcpy(szMSG,"A BRIGHT ");+V$; FLAGS[50]=1;}
 if(((ROOMID==ROOM_STABLE) && (OBJID==OBJ_DOOR))  &&  OBJLOC[OBJ_MATCHES]==ROOM_INVENTORY)
 { FLAGS[43]=1; strcpy(szMSG,"IT HAS TURNED TO ASHES");;}
}
void c_FUNCT_FILL()
{
 if((OBJID==OBJ_JUG  ||  OBJID==OBJ_BUCKET)  &&  (ROOMID==ROOM_ROUGH_WATER  ||  ROOMID==ROOM_MIDDLE_OF_THE_LAKE))
 { strcpy(szMSG,"YOU CAPSIZED!");; FLAGS[56]=1;}
 if(((ROOMID==ROOM_STREAM_IN_A_VALLEY_BOTTOM) && (OBJID==OBJ_JUG))  &&  OBJLOC[OBJ_JUG]==ROOM_INVENTORY)
 { strcpy(szMSG,"IT IS NOW FULL");; FLAGS[34]=1;}
 if(((ROOMID==ROOM_STREAM_IN_A_VALLEY_BOTTOM) && (OBJID==OBJ_BUCKET)))
 { strcpy(szMSG,"IT LEAKS OUT!");;}
}
void c_FUNCT_PLANT()
{
 if(OBJID!==OBJ_SEEDS  ||  ROOMID!==ROOM_HIGHWALLED_GARDEN)
 { strcpy(szMSG,"DO NOT GROW!");; return;;}
 strcpy(szMSG,"OK");; FLAGS[37]=1
}
void c_FUNCT_WATER()
{
 if(OBJID==OBJ_SEEDS  &&  FLAGS[37]==1  &&  FLAGS[34]==1)
 { strcpy(szMSG,"A LARGE VINE GROWS IN SECONDS!");; FLAGS[38]=1; ;}
}
void c_FUNCT_SWING()
{
 if(OBJID==OBJ_AXE  ||  OBJID==OBJ_SWORD)
 { strcpy(szMSG,"THWACK!");;}
 if(((ROOMID==ROOM_COBWEBBY_ROOM) && (OBJID==OBJ_SWORD)))
 { strcpy(szMSG,"YOU CLEARED THE COBWEBS");; FLAGS[66]=1;}
 if(((ROOMID==ROOM_DANK_CORRIDOR) && (OBJID==OBJ_AXE)))
 { strcpy(szMSG,"THE DOOR BROKE!");; E$(18)="NS"; E$(28)="NS";}
 if(((ROOMID==ROOM_DAMP_WELL_BOTTOM) && (OBJID==OBJ_AXE)))
 { strcpy(szMSG,"YOU BROKE THROUGH");; E$(71)="N";}
}
void c_FUNCT_EMPTY()
{
 if(OBJID==OBJ_JUG)
 { OBJID=OBJ_SEEDS; FUNCT_WATER();}
 if(((ROOMID==ROOM_MOSAICFLOORED_HALL) && (OBJID==OBJ_PHIAL)))
 { strcpy(szMSG,"WHERE?");;}
}
void c_FUNCT_ENTER()
{
 if(((ROOMID==ROOM_55OUTSIDE_A_WINDMILL) && (OBJID==OBJ_WINDMILL)))
 { VERBID=VERB_EAST; FUNCT_MOVE(); return;;}
 if(ROOMID==ROOM_MOUNTAIN_HUT)
 { strcpy(szMSG,"YOU FOND SOMETHING");; FLAGS[OBJ_PLANKS]=OBJ_STATUS_VISIBLE;}
}
void c_FUNCT_CROSS()
{
 if(ROOMID==ROOM_EAST_END_OF_A_BRIDGE)
 { VERBID=VERB_WEST; FUNCT_MOVE(); return;;}
 if(ROOMID==ROOM_WEST_END_OF_A_BRIDGE)
 { VERBID=VERB_EAST; FUNCT_MOVE();}
}
void c_FUNCT_REMOVE()
{
 if((OBJID==OBJ_BOOTS  &&  FLAGS[29]==1))
 { strcpy(szMSG,"TAKEN OFF");; FLAGS[29]=0;}
 if((OBJID==OBJ_UNIFORM  &&  FLAGS[51]==1))
 { strcpy(szMSG,"OK");; FLAGS[51]=0;}
 if(OBJID==OBJ_BRICKS  ||  OBJID==OBJ_RUBBLE)
 { FUNCT_MOVE();}
}
void c_FUNCT_FEED()
{
 if(((ROOMID==ROOM_WINE_CELLAR) && (OBJID==OBJ_RATS))  ||  ((ROOMID==ROOM_RUSTY_GATES) && (OBJID==OBJ_PONY))  ||  ((ROOMID==ROOM_OVERGROWN_TRACK) && (OBJID==OBJ_PONY))  ||  ((ROOMID==ROOM_BARREN_COUNTRYSIDE) && (OBJID==OBJ_OGBANS_BOAR))  ||  ((ROOMID==ROOM_HIGH_GLASS_GATES) && (OBJID==OBJ_HOUND)))
 { strcpy(szMSG,"WITH WHAT?");;}
}
void c_FUNCT_TURN()
{
 if(((ROOMID==ROOM_DISUSED_WATERWHEEL) && (OBJID==OBJ_WHEEL)))
 { strcpy(szMSG,"IT GOES ROUND");;}
 if(((ROOMID==ROOM_SLUICE_GATES) && (OBJID==OBJ_HANDLE)))
 { strcpy(szMSG,"THE GATES OPEN, THE POOL EMPTIES");; FLAGS[33]=1; ;}
}
void c_FUNCT_DIVE()
{
 if(ROOMID==ROOM_MISTY_POOL  ||  ROOMID==ROOM_MIDDLE_OF_THE_LAKE)
 { strcpy(szMSG,"YOU HAVE DROWNED");; FLAGS[56]=1;}
}
void c_FUNCT_BAIL()
{
 strcpy(szMSG,"HOW?");; return;
void c_FUNCT_LEAVE()
{
 if(OBJID==0  ||  OBJID>TOBJCOUNT)
 { return;;}
 OBJLOC[OBJID]=ROOMID; strcpy(szMSG,"DONE");
 if(((ROOMID==ROOM_ROUGH_WATER) && (OBJID==OBJ_BOAT))  ||  ((ROOMID==ROOM_MIDDLE_OF_THE_LAKE) && (OBJID==OBJ_BOAT)))
 { strcpy(szMSG,"YOU DROWNED!");; FLAGS[56]=1;}
 if(OBJID==OBJ_BOAT  &&  FLAGS[30]==1)
 { OBJLOC[OBJ_SHEET]=ROOMID;}
 if(OBJID==OBJ_JUG  &&  FLAGS[34]==1)
 { strcpy(szMSG,"YOU LOST THE WATER!");; FLAGS[34]=0;}
 if(OBJID==OBJ_SHEET  &&  FLAGS[30]==1)
 { FLAGS[30]=0;}
}
void c_FUNCT_INSERT()
{
 if(OBJID==OBJ_COIN  &&  FLAGS[44]==0)
 { strcpy(szMSG,"YOU DO NOT HAVE ANY");;}
 if(((ROOMID==ROOM_TURRET_ROOM_WITH_A_SLOT_MACHINE) && (OBJID==OBJ_COIN))  &&  OBJLOC[OBJ_COINS]==ROOM_INVENTORY  &&  FLAGS[44]>0)
 { funct_3230();}
}
void c_FUNCT_THROW()
{
 if(OBJID==0  ||  OBJID>TOBJCOUNT)
 { return;;}
 strcpy(szMSG,"DID NOT GO FAR!");; OBJLOC[OBJID]=ROOMID
 if(((ROOMID==ROOM_BARREN_COUNTRYSIDE) && (OBJID==OBJ_NET)))
 { strcpy(szMSG,"YOU CAUGHT THE BOAR");; FLAGS[32]=1; ;}
}
void c_FUNCT_RIG()
{
 if(OBJID==OBJ_REEDS)
 { strcpy(szMSG,"A NICE TUNE");; ;}
 if(((ROOMID==ROOM_EDGE_OF_AN_ICY_LAKE) && (OBJID==OBJ_SAIL)))
 { strcpy(szMSG,"WHAT WITH?");;}
 if(OBJID==OBJ_MUSIC)
 { strcpy(szMSG,"HOW, O MUSICAL ONE?");;}
 if(((ROOMID==ROOM_HUGE_FALLEN_OAK) && (OBJID==OBJ_REEDS)))
 { FLAGS[35]=1; strcpy(szMSG,"THE GHOST OF THE GOBLIN GUARDIAN IS FREE");; E$(56)="NS";}
}
void c_FUNCT_EAT()
{
 if(OBJID==0  ||  OBJID>TOBJCOUNT)
 { return;;}
 if(OBJID==OBJ_APPLES  ||  OBJID==OBJ_BREAD)
 { strcpy(szMSG,"YUM YUM!");; OBJLOC[OBJID]=ROOM_NOWHERE;}
}
void c_FUNCT_MOVE()
{
 if(ROOMID==ROOM_STALACTITES_AND_STALAGMITES  &&  OBJID==OBJ_RUBBLE)
 { FLAGS[45]=1; strcpy(szMSG,"YOU REVEALED A STEEP PASSAGE");;}
 if(ROOMID==ROOM_HOLLOW_TOMB  &&  OBJID==OBJ_RUBBLE)
 { strcpy(szMSG,"YOU CANNOT MOVE RUBBLE FROM HERE");;}
 if(((ROOMID==ROOM_DAMP_WELL_BOTTOM) && (OBJID==OBJ_BRICKS)))
 { strcpy(szMSG,"THEY ARE WEDGED IN!");;}
}
void c_FUNCT_INTO()
{
 if((OBJID==OBJ_GOBLET  ||  OBJID==OBJ_WINE)  &&  OBJLOC[OBJ_PHIAL]==ROOM_INVENTORY  &&  ROOMID==ROOM_MOSAICFLOORED_HALL)
 { strcpy(szMSG,"OK");; FLAGS[47]=1;}
}
void c_FUNCT_RING()
{
 if(ROOMID!==ROOM_SILVER_BELL_IN_THE_ROCK  ||  OBJID!==OBJ_BELL)
 { return;;}
funct_3020()
 PRINT(); ; PRINT("HOW MANY TIMES?"); INPUT MR; if(MR==0)
 { PRINT("A NUMBER"); GOTO funct_3020;}
 if(MR==FLAGS[42])
 { strcpy(szMSG,"A ROCK DOOR OPENS");; E$(27)="EW"; return;;}
 strcpy(szMSG,"YOU HAVE MISTREATED THE BELL!");; FLAGS[56]=1; ; return;
void c_FUNCT_CUT()
{
 if(((ROOMID==ROOM_COBWEBBY_ROOM) && (OBJID==OBJ_COBWEBS)))
 { ((ROOMID=ROOM_COBWEBBY_ROOM)AND(OBJID=OBJ_SWORD)); FUNCT_SWING();}
}
void c_FUNCT_HOLD()
{
 if((((ROOMID==ROOM_WIZARDS_LAIR) && (OBJID==OBJ_UP_SILVER_PLATE))  ||  ((ROOMID==ROOM_WIZARDS_LAIR) && (OBJID==OBJ_SILVER_PLATE)))  &&  OBJLOC[OBJ_SILVER_PLATE]==ROOM_INVENTORY)
 { strcpy(szMSG,"YOU REFLECTED THE WIZARD'S GLARE! HE IS DEAD");; FLAGS[63]=1; ;}
 if(OBJID==OBJ_STONE_OF_DESTINY)
 { FUNCT_GET();}
}
void c_FUNCT_PAY()
{
 if(((ROOMID==ROOM_WEST_END_OF_A_BRIDGE) && (OBJID==OBJ_TROLL))  ||  ((ROOMID==ROOM_EAST_END_OF_A_BRIDGE) && (OBJID==OBJ_TROLL)))
 { strcpy(szMSG,"WHAT WITH?");;}
 if(OBJID==OBJ_COINS  ||  OBJID==OBJ_COIN)
 { FUNCT_GIVE();}
}
void c_FUNCT_UNLOCK()
{
 if(((ROOMID==ROOM_WIZARDS_LAIR) && (OBJID==OBJ_DOOR))  &&  OBJLOC[OBJ_KEY]==ROOM_INVENTORY)
 { strcpy(szMSG,"THE KEY TURNS!");; FLAGS[70]=1;}
}
void c_FUNCT_BREAK()
{
 if(((ROOMID==ROOM_DANK_CORRIDOR) && (OBJID==OBJ_DOOR)))
 { strcpy(szMSG,"HOW?");;}
}
void c_FUNCT_REFLECT()
{
 if(ROOMID==ROOM_WIZARDS_LAIR)
 { strcpy(szMSG,"HOW?");;}
}
void c_FUNCT_DRINK()
{
 strcpy(szMSG,"ARE YOU THIRSTY?");
}
funct_3210()
 strcpy(szMSG,"HE TAKES IT AND SAYS '");+STR$ (FLAGS[42])+" RINGS ARE NEEDED'"; OBJLOC[OBJ_BROOCH]=ROOM_NOWHERE
}
funct_3230()
 FLAGS[44]=FLAGS[44]-1; strcpy(szMSG,"A NUMBER APPEARS - ");+STR$ (FLAGS[41])
 if(FLAGS[44]==0)
 { OBJLOC[OBJ_COINS]=ROOM_NOWHERE;}
}
funct_3260()
 PRINT(); ; strcpy(szMSG,"WHAT IS THE CODE");; ; PRINT(R$); INPUT CN
 strcpy(szMSG,"WRONG!");; if(CN==FLAGS[41])
 { strcpy(szMSG,"IT OPENS");; FLAGS[OBJ_KEY]=OBJ_STATUS_VISIBLE;}
}
funct_3290()
 T=ROOMID; ROOMID=FLAGS[FLAGS[52]+57]; funct_3310(); ROOMID=T
 strcpy(szMSG,"MAGIC WORDS LIE AT THE CROSSROADS, THE FOUNTAIN AND THE ");+D$(3 TO ); return;
funct_3310()
 X=INT ((ROOMID-1)/2)+1
 RESTORE X*10+3620
 FOR I=0 TO ROOMID-X*2+1
 READ D$; NEXT I
}
funct_3330()
 RESTORE 4030
}
funct_3350()
 O$=O$(2 TO ); return;
funct_3360()
 PRINT("PRESS ENTER TO CONTINUE");
 INPUT Z$; return;
funct_3380()
 DIM OBJLOC[TOBJCOUNT]; DIM E$(ROOMCOUNT,4); DIM FLAGS[70]; DIM X$(6,4); DIM Y$(6,7); DIM G$(2,8); DIM X(VERBCOUNT+1)
 funct_3330()
 FOR I=1 TO OBJCOUNT; READ T$; NEXT I
 FOR I=1 TO 6; READ X$(I),Y$(I); NEXT I
 VERBS$="NOOEOOSOOWOOUOODOOINVGETTAKEXAREAGIVSAYPICWEATIECLIRIGUSEOPE"
 VERBS$=VERBS$+"LIGFILPLAWATSWIEMPENTCROREMFEETURDIVBAILEATHRINSBLODROEATMOV"
 VERBS$=VERBS$+"INTRINCUTHOLBURPOISHOUNLWITDRICOUPAYMAKBRESTEGATREF"
 funct_5000()
 funct_4400(); PRINT("DO YOU WANT TO");
 PRINT(); ; PRINT(" 1. START A NEW GAME");
 PRINT("OR 2. CONTINUE A SAVED GAME");
funct_3580()
 PRINT(); ; PRINT(); ; PRINT("TYPE IN EITHER 1 OR 2");
 INPUT C; if(C!==1  &&  C!==2)
 { GOTO funct_3580;}
 if(C==1)
 { funct_4450();}
 if(C==2)
 { funct_4600();}
}
 DATA "11HALF-DUG GRAVE","12GOBLIN GRAVEYARD"
 DATA "11HOLLOW TOMB","23STALACTITES AND STALAGMITES"
 DATA "11MAZE OF TUNNELS","11VAULTED CAVERN"
 DATA "23HIGH GLASS GATES","12ENTRANCE HALL TO THE PALACE"
 DATA "31GRARG SENTRY POST","12GUARD ROOM"
 DATA "31MARSHY INLET","23RUSTY GATES"
 DATA "12GAMEKEEPER'S COTTAGE","31MISTY POOL"
 DATA "11HIGH-WALLED GARDEN","14INSCRIBED CAVERN"
 DATA "34ORNATE FOUNTIAN","11DANK CORRIDOR"
 DATA "12LONG GALLERY","12KITCHENS OF THE PALACE"
 DATA "34OLD KILN","44OVERGROWN TRACK"
 DATA "31DISUSED WATERWHEEL","33SLUICE GATES"
 DATA "11GAP BETWEEN SOME BOULDERS","41PERILOUS PATH"
 DATA "31SILVER BELL IN THE ROCK","12DUNGEONS OF THE PALACE"
 DATA "11BANQUETING HALL","42PALACE BATTLEMENTS"
 DATA "44ISLAND SHORE","31BEACHED KETCH"
 DATA "13BARREN COUNTRYSIDE","33SACKS ON THE UPPER FLOOR"
 DATA "46FROZEN POND","21MOUNTAIN HUT"
 DATA "31ROW OF CASKS","11WINE CELLAR"
 DATA "12HALL OF TAPESTRIES","11DUSTY LIBRARY"
 DATA "13ROUGH WATER","11PLOUGHED FIELD"
 DATA "55OUTSIDE A WINDMILL","42LOWER FLOOR OF THE MILL"
 DATA "44ICY PATH","41SCREE SLOPE"
 DATA "12SILVER CHAMBER","12WIZARD'S LAIR"
 DATA "11MOSAIC-FLOORED HALL","12SILVER THRONE ROOM"
 DATA "12MIDDLE OF THE LAKE","42EDGE OF AN ICY LAKE"
 DATA "41PITTED TRACK","41HIGH PINNACLE"
 DATA "55ABOVE A GLACIER","21 HUGE FALLEN OAK"
 DATA "11TURRET ROOM WITH A SLOT MACHINE","11COBWEBBY ROOM"
 DATA "31SAFE IN OGBAN'S CHAMBER","31CUPBOARD IN A CORNER"
 DATA "11NARROW PASSAGE","16CAVE"
 DATA "11WOODMAN'S HUT","42SIDE OF A WOODED VALLEY"
 DATA "21STREAM IN A VALLEY BOTTOM","11DEEP DARK WOOD"
 DATA "11SHADY HOLLOW","34ANCIENT STONE CIRCLE"
 DATA "16STABLE","14ATTIC BEDROOM"
 DATA "11DAMP WELL BOTTOM","32TOP OF A DEEP WELL"
 DATA "31BURNT-OUT CAMPFIRE","16ORCHARD"
 DATA "62END OF A BRIDGE","62END OF A BRIDGE"
 DATA "61CROSSROADS","41WINDING ROAD"
 DATA "11VILLAGE OF RUSTIC HOUSES","11WHITE COTTAGE"
 DATA "3COINS","1SHEET","3BOOTS","1HORSESHOE","3APPLES","1BUCKET","4AXE","1BOAT","1PHIAL"
 DATA "3REEDS","1BONE","1SHIELD","3PLANKS","1ROPE","1RING","1JUG","1NET","1SWORD"
 DATA "1SILVER PLATE","1UNIFORM","1KEY","3SEEDS","1LAMP","3BREAD","1BROOCH","3MATCHES"
 DATA "2STONE OF DESTINY","4APPLE","BED","CUPBOARD","BRIDGE","TREES","SAIL","KILN"
 DATA "KETCH","BRICKS","WINDMILL","SACKS","OGBAN'S BOAR","WHEEL"
 DATA "PONY","GRAVESTONES","POOL","GATES","HANDLE","HUT","VINE","INSCRIPTIONS","TROLL","RUBBLE"
 DATA "HOUND","FOUNTAIN","CIRCLE","MOSAICS","BOOKS","CASKS","WELL","WALLS","RATS","SAFE"
 DATA "COBWEBS","COIN","BELL","UP SILVER PLATE","STONES","KITCHENS","GOBLET","WINE"
 DATA "GRARGS","DOOR","AWAKE","GUIDE","PROTECT","LEAD","HELP","CHEST","WATER"
 DATA "STABLES","SLUICE GATES","POT","STATUE","PINNACLE","MUSIC","MAGIC WORDS"
 DATA "MISTY POOL","WELL BOTTOM","OLD KILN","MOUNTIAN HUT"
 DATA "IN","A","NEAR","THE","BY","SOME","ON","AN","","","AT","A SMALL"
 DATA "E","ESW","WE","EW","EW","ESW","ESW","ES","EW","SW"
 DATA "S","N","ES","SW","S","NW","N","N","ES","NSW"
 DATA "NS","E","NSW","N","NES","EW","W","S","NS","N"
 DATA "NES","W","NS","D","NES","SW","E","NW","NS","S"
 DATA "NS","E","NSEW","WU","UD","NS","E","SW","NSE","NW"
 DATA "NE","EW","NSW","E","WN","S","E","NEW","NW","S"
 DATA "ES","SW","NES","EW","SW","NE","EW","ESW","SW","ND"
 DATA ".","E","NEW","EW","NEW","EW","EW","NEW","NEW","WU"
 DATA 80,70,60,69,74,72,63,52,20,11,1,14,36,54,61,21,32,10,50
 DATA 29,59,34,13,80,30,81,47,74
 DATA 1,2,3,4,5,9,12,13,16,17,20,21,22
 Z$=""; FOR I=1 TO LEN(R$)
 C$=R$(I); if(C$<"A")
 { Z$=Z$+C$; GOTO funct_4300;}
 C=CODE (C$)-1; if(C==64)
 { C=90;}
 Z$=Z$+CHR$ (C)
funct_4300()
 NEXT I; R$=Z$; return;
funct_4310()
 J$="SSSSSSSS"; NG=0
funct_4320()
 MP=DIRID/2; funct_4400()
 PRINT("YOU ARE LOST IN THE TUNNELS");
 PRINT("WHICH WAY? (N,S,E,W)");
 if(NG>15)
 { PRINT("(OR G TO GIVE UP!)");}
 PRINT(); ; INPUT W$; J$=(J$+W$(1))(2 TO )
 if(W$=="G")
 { FLAGS[56]=1; return;;}
 if(J$!==G$(MP))
 { NG=NG+1; GOTO funct_4320;}
}
funct_4400()
 CLS ; PRINT();
 PRINT TAB (SCREENWIDTH/2-9);"MYSTERY OF SILVER");
 PRINT TAB (SCREENWIDTH/2-9);" MOUNTAIN");
 PRINT("================================");
 PRINT(); ; PRINT(); ; return;
funct_4450()
 FOR I=1 TO ROOMCOUNT; READ E$(I); NEXT I
 FOR I=1 TO TOBJCOUNT; READ OBJLOC[I]; NEXT I
 FOR I=1 TO 13; READ A; FLAGS[A]=1; NEXT I
 FLAGS[41]=INT (RND*900)+100; FLAGS[42]=INT (RND*3)+2
 FLAGS[44]=4; FLAGS[57]=68; FLAGS[58]=54; FLAGS[59]=15; FLAGS[52]=INT (RND*3)
 ROOMID=ROOM_CROSSROADS; strcpy(szMSG,"GOOD LUCK ON YOUR QUEST!");
 G$(1)=""; FOR I=1 TO 8
 F$=VERBS$(1+INT (RND*4)*3)
 G$(1)=G$(1)( TO I-1)+F$
 if(F$=="N")
 { L$="S";}
 if(F$=="S")
 { L$="N";}
 if(F$=="E")
 { L$="W";}
 if(F$=="W")
 { L$="E";}
 G$(2)=L$+G$(2)( TO I-1)
 NEXT I; return;
funct_4600()
 funct_4640(); funct_4670()
 ROOMID=FLAGS[69]; strcpy(szMSG,"OK. CARRY ON");
}
funct_4630()
 FLAGS[69]=ROOMID; funct_4640(); funct_4760(); PRINT("BYE..."); STOP
funct_4640()
 PRINT(); ; PRINT("ENTER FILE NAME"); INPUT F$
}
 REM READ DATA FILE
funct_4670()
 REM
 PRINT("OK.SEARCHING FOR ",F$);
 LOAD F$+"(E$)" DATA E$()
 LOAD F$+"(C)" DATA OBJLOC[]
 LOAD F$+"(F)" DATA FLAGS[]
 LOAD F$+"(G$)" DATA G$()
}
 REM SAVE DATA FILE
funct_4760()
 REM
 SAVE F$+"(E$)" DATA E$()
 SAVE F$+"(C)" DATA OBJLOC[]
 SAVE F$+"(F)" DATA FLAGS[]
 SAVE F$+"(G$)" DATA G$()
}
funct_4830()
 LS=1; LP=1
 FOR I=1 TO LEN(J$)
 if(J$(I)==" "  &&  LL>SCREENWIDTH)
 { PRINT( J$(LP TO LS-1)); LL=I-LS; LP=LS+1;}
 if(J$(I)==" ")
 { LS=I;}
 LL=LL+1; NEXT I
 PRINT(J$(LP TO ));
}
funct_4900()
 P$=Y$(VAL (O$(1))); funct_3350()
funct_4910()
 if(P$(LEN(P$))==" ")
 { P$=P$( TO LEN(P$)-1); GOTO funct_4910;}
 J$=J$+" "+P$+" "+O$+","
}
funct_5000()
 RESTORE 6000; FOR I=1 TO VERBCOUNT+1
 READ X(I); NEXT I
 RESTORE 4150; return;
 DATA 800,800,800,800,800,800,1220,1290,1290,1470,1470,1750,1890
 DATA 1960,1980,2010,2050,2870,2120,2220,2310,2380,2420,2450,2470,2520
 DATA 2550,2580,2610,2650,2670,2700,2720,2730,2830,2800,2870,2730,2920
 DATA 2950,2990,3010,3050,3070,2310,2990,3070,3130,2120,3190,1470,3100
 DATA 2870,3150,1290,1290,3170,3200 